Repository sourcenetwork/defradb, pull requests merged in 2023-11, with the labels that each got.

#2016 refactor: CRDT merge direction
  Makefile
  core/clock.go
  core/crdt/composite.go
  db/fetcher/versioned.go
  merkle/clock/clock.go
  net/dag.go
  net/dag_test.go
  net/process.go
  net/server.go
  net/server_test.go
Labels: area/crdt, refactor

#2037 fix: Fix test module relying on closed memory leak
  tests/lenses/rust_wasm32_copy/src/lib.rs
Labels: area/schema, area/testing

#2035 ci: Add mac test runner
  .github/workflows/test-and-upload-coverage.yml
Labels: area/testing, ci/build, action/no-benchmark

#2044 chore: Update dependencies
  cli/start.go
  core/parser.go
  datastore/badger/v4/datastore.go
  datastore/badger/v4/datastore_test.go
  datastore/badger/v4/iterator.go
  datastore/concurrent_txt_test.go
  datastore/txn_test.go
  datastore/wrappedstore_test.go
  db/db_test.go
  go.mod
  go.sum
  net/dialer.go
  net/node.go
  net/node_test.go
  net/peer_test.go
  net/server.go
  net/server_test.go
  planner/doc.go
  request/graphql/parser.go
  request/graphql/parser/commit.go
  request/graphql/parser/filter.go
  request/graphql/parser/introspection.go
  request/graphql/parser/mutation.go
  request/graphql/parser/query.go
  request/graphql/parser/request.go
  request/graphql/parser/subscription.go
  request/graphql/schema/collection.go
  request/graphql/schema/descriptions.go
  request/graphql/schema/generate.go
  request/graphql/schema/manager.go
  request/graphql/schema/types/base.go
  request/graphql/schema/types/commits.go
  request/graphql/schema/types/types.go
  tests/bench/bench_util.go
  tests/integration/db.go
  tests/integration/net/order/utils.go
  tests/integration/p2p.go
Labels: dependencies

#2040 ci: Add goreleaser workflow
  .github/workflows/pull-docker-image.yml
  .github/workflows/push-docker-image-to-registries.yml
  .github/workflows/release.yml
  .goreleaser.yaml
  tools/goreleaser.containerfile
Labels: ci/build

#2030 perf: Switch LensVM to wasmtime runtime
  .github/workflows/test-and-upload-coverage.yml
  go.mod
  go.sum
  lens/registry.go
Labels: area/schema, perf

#2033 ci: Add windows test runner
  .github/workflows/test-and-upload-coverage.yml
  config/configfile_test.go
  datastore/badger/v4/datastore_test.go
  datastore/memory/memory_test.go
  db/index_test.go
  db/indexed_docs_test.go
  http/errors.go
  http/server.go
  http/server_test.go
  logging/logging_test.go
  net/client_test.go
  net/dialer_test.go
  net/node_test.go
  net/peer_test.go
  tests/integration/backup/simple/export_test.go
  tests/integration/backup/simple/import_test.go
Labels: area/testing, ci/build, code quality

#2051 test: Add auto-doc generation
  client/descriptions.go
  tests/gen/README.md
  tests/gen/defs.go
  tests/gen/errors.go
  tests/gen/gen_auto.go
  tests/gen/gen_auto_config.go
  tests/gen/gen_auto_configurator.go
  tests/gen/gen_auto_option.go
  tests/gen/gen_auto_test.go
  tests/gen/schema_parser.go
  tests/gen/schema_parser_test.go
  tests/integration/index/docs.go
  tests/integration/index/query_performance_test.go
  tests/integration/index/query_with_index_combined_filter_test.go
  tests/integration/index/query_with_index_only_filter_test.go
  tests/integration/index/query_with_relation_filter_test.go
  tests/integration/index/utils.go
  tests/integration/test_case.go
  tests/integration/utils2.go
  tests/predefined/README.md
  tests/predefined/defs.go
  tests/predefined/errors.go
  tests/predefined/gen_predefined.go
  tests/predefined/gen_predefined_test.go
  tests/predefined/util_test.go
Labels: area/testing

#2083 chore: Update Lens to v0.5
  .github/workflows/test-and-upload-coverage.yml
  go.mod
  go.sum
  tests/lenses/rust_wasm32_copy/Cargo.toml
  tests/lenses/rust_wasm32_copy/src/lib.rs
  tests/lenses/rust_wasm32_remove/Cargo.toml
  tests/lenses/rust_wasm32_remove/src/lib.rs
  tests/lenses/rust_wasm32_set_default/Cargo.toml
  tests/lenses/rust_wasm32_set_default/src/lib.rs
Labels: area/query, area/schema, bump
