Repository sourcenetwork/defradb, pull requests merged in 2023-06, with the labels that each got.

#1450 feat: Non-unique secondary index
  .github/codecov.yml
  client/collection.go
  client/descriptions.go
  client/index.go
  core/key.go
  core/key_test.go
  datastore/mocks/DAGStore.go
  datastore/mocks/DSReaderWriter.go
  datastore/mocks/Results.go
  datastore/mocks/RootStore.go
  datastore/mocks/Txn.go
  datastore/mocks/utils.go
  db/collection.go
  db/collection_get.go
  db/collection_index.go
  db/errors.go
  db/fetcher/encoded_doc.go
  db/fetcher/fetcher.go
  db/fetcher/mocks/EncodedDocument.go
  db/fetcher/mocks/Fetcher.go
  db/fetcher/mocks/utils.go
  db/index.go
  db/index_test.go
  db/indexed_docs_test.go
  request/graphql/parser.go
  request/graphql/parser/request.go
  request/graphql/schema/collection.go
  request/graphql/schema/descriptions_test.go
  request/graphql/schema/errors.go
  request/graphql/schema/index_test.go
  request/graphql/schema/manager.go
  request/graphql/schema/types/types.go
  tests/README.md
  tests/integration/index/create_drop_test.go
  tests/integration/index/create_get_test.go
  tests/integration/index/create_test.go
  tests/integration/index/drop_test.go
  tests/integration/index/get_test.go
  tests/integration/net/state/simple/peer/subscribe/with_add_remove_test.go
  tests/integration/net/state/simple/peer/subscribe/with_add_test.go
  tests/integration/p2p.go
  tests/integration/schema/updates/index/simple_test.go
  tests/integration/test_case.go
  tests/integration/utils2.go
Labels: feature, area/api

#1579 feat: Add alias to `groupBy` related object
  client/request/consts.go
  client/request/select.go
  db/collection_update.go
  planner/mapper/errors.go
  planner/mapper/mapper.go
  planner/type_join.go
  tests/integration/query/one_to_many/with_group_related_id_alias_test.go
  tests/integration/query/one_to_many/with_group_related_id_test.go
  tests/integration/query/one_to_many/with_related_id_test.go
  tests/integration/query/simple/with_group_test.go
  tests/integration/schema/group_test.go
Labels: feature, area/testing, priority/high

#1500 refactor: Fetcher filter and field optimization
  client/descriptions.go
  core/data.go
  db/collection.go
  db/collection_get.go
  db/collection_index.go
  db/collection_update.go
  db/fetcher/encoded_doc.go
  db/fetcher/errors.go
  db/fetcher/fetcher.go
  db/fetcher/mocks/EncodedDocument.go
  db/fetcher/mocks/Fetcher.go
  db/fetcher/mocks/utils.go
  db/fetcher/versioned.go
  db/fetcher_test.go
  db/indexed_docs_test.go
  go.mod
  go.sum
  net/process.go
  planner/commit.go
  planner/datasource.go
  planner/mapper/errors.go
  planner/mapper/mapper.go
  planner/mapper/targetable.go
  planner/planner.go
  planner/scan.go
  planner/sum.go
  planner/top.go
  planner/type_join.go
  request/graphql/parser/errors.go
  request/graphql/parser/filter.go
  tests/integration/explain/default/delete_test.go
  tests/integration/explain/execute/create_test.go
  tests/integration/explain/execute/delete_test.go
  tests/integration/explain/execute/group_test.go
  tests/integration/explain/execute/scan_test.go
  tests/integration/explain/execute/top_level_test.go
  tests/integration/explain/execute/type_join_test.go
  tests/integration/explain/execute/update_test.go
  tests/integration/explain/execute/with_average_test.go
  tests/integration/explain/execute/with_count_test.go
  tests/integration/explain/execute/with_limit_test.go
  tests/integration/explain/execute/with_order_test.go
  tests/integration/explain/execute/with_sum_test.go
  tests/integration/query/one_to_many/with_group_related_id_alias_test.go
  tests/integration/query/one_to_one_to_one/with_order_test.go
  tests/integration/query/simple/with_group_test.go
Labels: area/datastore, area/db-system, refactor, action/no-benchmark
