Repository sourcenetwork/defradb, pull requests merged in 2023-04, with the labels that each got.

#1352 fix: Guarantee event processing order
  events/events.go
  events/simple.go
Labels: bug, area/db-system, action/no-benchmark

#1344 ci: Bump go version within packer for AWS AMI
  .github/workflows/build-ami-with-packer.yml
  tools/cloud/aws/packer/build_aws_ami.pkr.hcl
Labels: bug, ci/build, action/no-benchmark, dependencies

#1359 fix: Use ring-buffer for WaitForFoo chans
  node/node.go
Labels: bug, area/p2p, action/no-benchmark

#1362 fix: Improve NonNull error message
  request/graphql/schema/collection.go
  request/graphql/schema/errors.go
  tests/integration/schema/simple_test.go
Labels: bug, area/query, area/schema, action/no-benchmark

#1363 chore: Document collection.txn
  db/collection.go
Labels: area/collections, code quality, action/no-benchmark

#1364 feat: Strongly type Request.Errors
  client/db.go
  db/request.go
  db/subscriptions.go
  db/txn_db.go
  request/graphql/parser.go
  tests/integration/utils2.go
Labels: feature, area/query, action/no-benchmark

#1369 fix: Unlock replicator lock before returning error
  net/peer.go
Labels: bug, area/p2p, action/no-benchmark

#1380 test: Convert filter explain tests to new explain setup
  tests/integration/explain/default/basic_test.go
  tests/integration/explain/default/example_new_basic_test.go
  tests/integration/explain/default/example_new_join_test.go
  tests/integration/explain/default/utils.go
  tests/integration/explain/default/with_filter_key_test.go
  tests/integration/explain/default/with_filter_test.go
  tests/integration/explain/utils.go
Labels: area/testing, action/no-benchmark

#1392 ci: Allow CI to work from forked repo
  .github/workflows/code-test-coverage.yml
  .github/workflows/run-tests.yml
Labels: bug, ci/build, action/no-benchmark

#1390 fix: Do not commit if errors have been returned
  db/txn_db.go
  tests/integration/mutation/simple/create/simple_test.go
Labels: bug, area/query, action/no-benchmark

#1387 feat: Add descriptions to all system defined GQL stuff
  request/graphql/schema/descriptions.go
  request/graphql/schema/generate.go
  request/graphql/schema/manager.go
  request/graphql/schema/types/base.go
  request/graphql/schema/types/commits.go
  request/graphql/schema/types/descriptions.go
  request/graphql/schema/types/types.go
  tests/integration/mutation/simple/delete/multi_ids_test.go
  tests/integration/mutation/simple/update/with_filter_test.go
  tests/integration/query/simple/with_group_test.go
  tests/integration/query/simple/with_limit_offset_test.go
  tests/integration/query/simple/with_order_test.go
Labels: documentation, area/query, action/no-benchmark

#1401 fix: Serialize DB errors to json in http package
  api/http/handlerfuncs.go
  api/http/handlerfuncs_test.go
  api/http/request_result.go
Labels: bug, area/network, action/no-benchmark

#1393 chore: Move to ipfs boxo
  api/http/handlerfuncs.go
  api/http/handlerfuncs_test.go
  client/db.go
  core/crdt/composite.go
  core/crdt/lwwreg.go
  core/crdt/lwwreg_test.go
  datastore/blockstore.go
  datastore/blockstore_test.go
  datastore/dag.go
  datastore/store.go
  db/db.go
  db/db_test.go
  db/fetcher/versioned.go
  go.mod
  go.sum
  merkle/clock/clock.go
  merkle/clock/ipld.go
  net/peer.go
  net/process.go
  node/node.go
  planner/commit.go
Labels: action/no-benchmark, dependencies

#1396 chore: Move to gofrs/uuid
  client/dockey.go
  go.mod
  go.sum
Labels: action/no-benchmark, dependencies

#1388 fix: Improve P2P event handling
  net/peer.go
  net/server.go
  tests/integration/p2p.go
Labels: area/testing, area/p2p, action/no-benchmark

#1354 docs: Add codcov and go report card badges
  README.md
Labels: documentation, action/no-benchmark

#1397 chore: Makefile using test flags and timeout
  Makefile
Labels: action/no-benchmark

#1405 fix: Limit the size of http request bodies that we handle
  api/http/handlerfuncs.go
Labels: bug, area/network, action/no-benchmark

#1408 feat: Add allowed origins config
  README.md
  cli/start.go
  config/config.go
  config/configfile_yaml.gotmpl
Labels: area/api, action/no-benchmark, area/cli

#1419 fix: Fix typo in readme
  README.md
Labels: action/no-benchmark
