Repository sourcenetwork/defradb, pull requests merged in 2023-10, with the labels that each got.

#1922 ci(i): Fix the pull_request trigger and ci badge
  .github/workflows/test-and-upload-coverage.yml
  README.md
Labels: documentation

#1926 fix(i): Update fetcher mock
  db/fetcher/mocks/fetcher.go
  db/fetcher/mocks/utils.go
Labels: area/testing, code quality

#1938 fix: Node private key requires data directory
  cli/start.go
  cli/utils.go
  net/config.go
  net/config_test.go
  net/dialer_test.go
  net/node.go
  net/node_test.go
  net/peer_test.go
  tests/integration/state.go
  tests/integration/utils2.go
Labels: area/config

#1927 refactor: Remove net GRPC API
  cli/p2p_collection_add.go
  cli/p2p_collection_remove.go
  cli/start.go
  client/p2p.go
  config/config.go
  config/config_test.go
  config/configfile_yaml.gotmpl
  db/p2p_collection_test.go
  db/txn_db.go
  go.mod
  go.sum
  http/client.go
  http/handler.go
  http/handler_store.go
  net/config.go
  net/config_test.go
  net/dag_test.go
  net/dialer_test.go
  net/node.go
  net/node_test.go
  net/pb/Makefile
  net/pb/net.pb.go
  net/pb/net.proto
  net/pb/net_grpc.pb.go
  net/pb/net_vtproto.pb.go
  net/peer.go
  net/peer_test.go
  net/server_test.go
  tests/clients/cli/wrapper.go
  tests/clients/http/wrapper.go
  tests/integration/net/order/utils.go
  tests/integration/net/state/simple/replicator/with_create_update_test.go
  tests/integration/p2p.go
  tests/integration/utils2.go
Labels: area/api, refactor

#1924 refactor: P2P client interface
  README.md
  cli/p2p_collection_add.go
  cli/p2p_collection_getall.go
  cli/p2p_collection_remove.go
  cli/p2p_info.go
  cli/p2p_replicator_delete.go
  cli/p2p_replicator_getall.go
  cli/p2p_replicator_set.go
  cli/start.go
  cli/utils.go
  client/db.go
  client/p2p.go
  config/config.go
  db/backup_test.go
  db/db.go
  db/index_test.go
  db/p2p_collection.go
  db/p2p_collection_test.go
  db/replicator.go
  db/replicator_test.go
  db/txn_db.go
  http/client.go
  http/client_p2p.go
  http/errors.go
  http/handler.go
  http/handler_p2p.go
  http/handler_store.go
  http/middleware.go
  http/server.go
  http/server_test.go
  net/client_test.go
  net/dag_test.go
  net/errors.go
  net/node.go
  net/node_test.go
  net/peer.go
  net/peer_collection.go
  net/peer_replicator.go
  net/peer_test.go
  net/server_test.go
  tests/bench/collection/utils.go
  tests/bench/query/planner/utils.go
  tests/bench/query/simple/utils.go
  tests/clients/cli/wrapper.go
  tests/clients/clients.go
  tests/clients/http/wrapper.go
  tests/integration/client.go
  tests/integration/db.go
  tests/integration/explain.go
  tests/integration/lens.go
  tests/integration/net/order/utils.go
  tests/integration/net/state/simple/replicator/with_create_test.go
  tests/integration/p2p.go
  tests/integration/state.go
  tests/integration/utils2.go
Labels: area/api, refactor, area/p2p

#1957 feat: Remove collection from patch schema
  client/db.go
  db/collection.go
  db/schema.go
  tests/integration/net/state/simple/peer/with_create_add_field_test.go
  tests/integration/net/state/simple/peer/with_update_add_field_test.go
  tests/integration/net/state/simple/replicator/with_create_add_field_test.go
  tests/integration/net/state/simple/replicator/with_update_add_field_test.go
  tests/integration/schema/migrations/query/simple_test.go
  tests/integration/schema/migrations/query/with_dockey_test.go
  tests/integration/schema/migrations/query/with_p2p_test.go
  tests/integration/schema/migrations/query/with_restart_test.go
  tests/integration/schema/migrations/query/with_set_default_test.go
  tests/integration/schema/migrations/query/with_txn_test.go
  tests/integration/schema/migrations/query/with_update_test.go
  tests/integration/schema/updates/add/field/crdt/composite_test.go
  tests/integration/schema/updates/add/field/crdt/invalid_test.go
  tests/integration/schema/updates/add/field/crdt/lww_test.go
  tests/integration/schema/updates/add/field/crdt/none_test.go
  tests/integration/schema/updates/add/field/crdt/object_bool_test.go
  tests/integration/schema/updates/add/field/create_test.go
  tests/integration/schema/updates/add/field/create_update_test.go
  tests/integration/schema/updates/add/field/kind/bool_array_test.go
  tests/integration/schema/updates/add/field/kind/bool_nil_array_test.go
  tests/integration/schema/updates/add/field/kind/bool_test.go
  tests/integration/schema/updates/add/field/kind/datetime_test.go
  tests/integration/schema/updates/add/field/kind/dockey_test.go
  tests/integration/schema/updates/add/field/kind/float_array_test.go
  tests/integration/schema/updates/add/field/kind/float_nil_array_test.go
  tests/integration/schema/updates/add/field/kind/float_test.go
  tests/integration/schema/updates/add/field/kind/foreign_object_array_test.go
  tests/integration/schema/updates/add/field/kind/foreign_object_test.go
  tests/integration/schema/updates/add/field/kind/int_array_test.go
  tests/integration/schema/updates/add/field/kind/int_nil_array_test.go
  tests/integration/schema/updates/add/field/kind/int_test.go
  tests/integration/schema/updates/add/field/kind/invalid_test.go
  tests/integration/schema/updates/add/field/kind/none_test.go
  tests/integration/schema/updates/add/field/kind/string_array_test.go
  tests/integration/schema/updates/add/field/kind/string_nil_array_test.go
  tests/integration/schema/updates/add/field/kind/string_test.go
  tests/integration/schema/updates/add/field/simple_test.go
  tests/integration/schema/updates/add/field/with_filter_test.go
  tests/integration/schema/updates/add/field/with_index_sub_test.go
  tests/integration/schema/updates/add/field/with_introspection_test.go
  tests/integration/schema/updates/add/simple_test.go
  tests/integration/schema/updates/copy/field/simple_test.go
  tests/integration/schema/updates/copy/field/with_introspection_test.go
  tests/integration/schema/updates/copy/simple_test.go
  tests/integration/schema/updates/index/simple_test.go
  tests/integration/schema/updates/move/field/simple_test.go
  tests/integration/schema/updates/remove/fields/simple_test.go
  tests/integration/schema/updates/remove/simple_test.go
  tests/integration/schema/updates/replace/field/simple_test.go
  tests/integration/schema/updates/replace/simple_test.go
  tests/integration/schema/updates/test/add_field_test.go
  tests/integration/schema/updates/test/field/simple_test.go
  tests/integration/schema/with_update_set_default_test.go
Labels: feature, area/schema, code quality

#1965 feat: Remove CollectionDescription.Schema
  client/descriptions.go
  core/key.go
  db/collection.go
  db/description/errors.go
  db/description/schema.go
  db/index_test.go
  db/indexed_docs_test.go
  db/schema.go
  docs/data_format_changes/i1958-remove-col-description-schema.md
  planner/sum.go
Labels: feature, area/schema, area/collections, refactor, code quality

#1960 feat: Add OpenAPI route
  cli/start.go
  go.mod
  go.sum
  http/handler.go
  http/handler_ccip.go
  http/handler_ccip_test.go
  http/handler_collection.go
  http/handler_lens.go
  http/handler_p2p.go
  http/handler_store.go
  http/handler_tx.go
  http/openapi.go
  http/router.go
  http/server.go
  http/server_test.go
  tests/clients/cli/wrapper.go
  tests/clients/http/wrapper.go
  tests/integration/client.go
Labels: documentation, area/api

#1979 feat: Add Swagger UI to playground
  playground/package-lock.json
  playground/package.json
  playground/src/App.tsx
  playground/src/components/Plugin.tsx
  playground/src/components/SchemaLoadForm.tsx
  playground/src/components/SchemaPatchForm.tsx
  playground/src/index.css
  playground/src/lib/api.ts
Labels: feature

#1980 refactor: Add peerstore to multistore
  client/db.go
  client/mocks/collection.go
  client/mocks/db.go
  datastore/concurrent_txn.go
  datastore/mocks/txn.go
  datastore/multi.go
  datastore/store.go
  datastore/txn.go
  db/db.go
  http/client.go
  http/client_tx.go
  merkle/clock/clock_test.go
  merkle/crdt/factory.go
  merkle/crdt/factory_test.go
  merkle/crdt/merklecrdt_test.go
  net/node.go
  tests/bench/query/planner/utils.go
  tests/clients/cli/wrapper.go
  tests/clients/cli/wrapper_tx.go
  tests/clients/http/wrapper.go
  tests/clients/http/wrapper_tx.go
Labels: area/datastore, refactor, code quality

#1984 feat: Change GetCollectionBySchemaFoo funcs to return many
  cli/collection.go
  cli/errors.go
  client/db.go
  client/errors.go
  client/mocks/db.go
  db/collection.go
  db/txn_db.go
  http/client.go
  http/handler_store.go
  net/peer_collection.go
  net/server.go
  planner/commit.go
  tests/clients/cli/wrapper.go
  tests/clients/http/wrapper.go
Labels: feature, area/collections, code quality

#1986 feat: Enable playground in Docker build
  tools/defradb.containerfile
Labels: platforms

#2002 docs(i): Fix typos
  README.md
  db/backup.go
  db/fetcher/versioned.go
  db/indexed_docs_test.go
Labels: documentation

#1988 refactor: Reorganise collection description storage
  core/key.go
  core/parser.go
  db/collection.go
  db/description/collection.go
  db/description/errors.go
  db/description/schema.go
  db/index_test.go
  db/indexed_docs_test.go
  db/schema.go
  docs/data_format_changes/i1964-reorg-col-desc-storage.md
  net/peer_collection.go
  net/process.go
  tests/integration/backup/one_to_many/export_test.go
  tests/integration/backup/one_to_one/export_test.go
  tests/integration/net/state/simple/peer/subscribe/with_add_remove_test.go
  tests/integration/net/state/simple/peer/subscribe/with_add_test.go
Labels: area/collections, refactor, action/no-benchmark

#2006 feat: Add means to fetch schema
  cli/cli.go
  cli/schema_describe.go
  client/db.go
  client/mocks/db.go
  db/description/schema.go
  db/schema.go
  db/txn_db.go
  http/client.go
  http/handler_store.go
  http/openapi.go
  tests/clients/cli/wrapper.go
  tests/clients/http/wrapper.go
  tests/integration/schema/get_schema_test.go
  tests/integration/schema/simple_test.go
  tests/integration/schema/updates/add/field/simple_test.go
  tests/integration/test_case.go
  tests/integration/utils2.go
Labels: feature, area/schema, action/no-benchmark
