Repository sourcenetwork/defradb, pull requests merged in 2023-05, with the labels that each got.

#1424 chore: Improve logging consistency
  README.md
  api/http/errors.go
  api/http/handlerfuncs_test.go
  api/http/server.go
  cli/peerid.go
  cli/peerid_test.go
  cli/replicator_delete.go
  cli/replicator_set.go
  client/dockey.go
  db/collection.go
  net/client.go
  net/pb/net.proto
  net/peer.go
  net/server.go
  node/node.go
  tests/integration/cli/client_peerid_test.go
Labels: action/no-benchmark

#1416 test: Convert mutation explain tests to new explain setup
  tests/integration/explain/default/create_test.go
  tests/integration/explain/default/delete_test.go
  tests/integration/explain/default/delete_with_error_test.go
  tests/integration/explain/default/update_test.go
Labels: area/testing, action/no-benchmark

#1434 ci: Add a separate workflow to run the linter
  .github/workflows/lint.yml
Labels: ci/build, action/no-benchmark

#1426 ci: Fix the SSH security issue from AMI scan report
  .github/workflows/build-ami-with-packer.yml
  tools/cloud/aws/packer/build_aws_ami.pkr.hcl
Labels: ci/build, action/no-benchmark, security

#1433 test: Improve change detector performance
  docs/data_format_changes/i1186-change-detctor-setup.md
  tests/integration/change_detector.go
  tests/integration/explain/utils.go
  tests/integration/utils2.go
Labels: perf, ci/build, action/no-benchmark, area/cli

#1438 ci: Remove secret ssh key stuff from change detector wf
  .github/workflows/detect-change.yml
  tests/integration/utils2.go
Labels: area/testing, ci/build, action/no-benchmark

#1440 fix: Update QL documentation link and replicator command
  README.md
Labels: documentation

#1446 test: Convert explain limit tests to new explain setup
  tests/integration/explain/default/with_limit_count_test.go
  tests/integration/explain/default/with_limit_join_test.go
  tests/integration/explain/default/with_limit_test.go
Labels: area/testing, code quality

#1422 chore: Update graphql-go
  go.mod
  go.sum
  request/graphql/schema/generate.go
Labels: action/no-benchmark, dependencies

#1451 feat: Add commits fieldName and fieldId fields
  client/descriptions.go
  client/request/consts.go
  core/crdt/composite.go
  core/crdt/lwwreg.go
  core/crdt/lwwreg_test.go
  db/collection.go
  db/collection_delete.go
  db/collection_update.go
  db/fetcher/versioned.go
  docs/data_format_changes/i851-field-name-in-block.md
  merkle/clock/clock_test.go
  merkle/crdt/composite.go
  merkle/crdt/factory.go
  merkle/crdt/factory_test.go
  merkle/crdt/lwwreg.go
  merkle/crdt/merklecrdt_test.go
  net/process.go
  planner/commit.go
  planner/errors.go
  planner/planner.go
  request/graphql/schema/types/commits.go
  request/graphql/schema/types/descriptions.go
  tests/bench/query/planner/utils.go
  tests/integration/events/simple/with_update_test.go
  tests/integration/mutation/simple/create/with_version_test.go
  tests/integration/query/commits/simple_test.go
  tests/integration/query/commits/with_cid_test.go
  tests/integration/query/commits/with_depth_test.go
  tests/integration/query/commits/with_dockey_cid_test.go
  tests/integration/query/commits/with_dockey_count_test.go
  tests/integration/query/commits/with_dockey_field_test.go
  tests/integration/query/commits/with_dockey_limit_offset_test.go
  tests/integration/query/commits/with_dockey_limit_test.go
  tests/integration/query/commits/with_dockey_order_limit_offset_test.go
  tests/integration/query/commits/with_dockey_order_test.go
  tests/integration/query/commits/with_dockey_test.go
  tests/integration/query/commits/with_dockey_typename_test.go
  tests/integration/query/commits/with_field_test.go
  tests/integration/query/commits/with_group_test.go
  tests/integration/query/latest_commits/with_dockey_field_test.go
  tests/integration/query/latest_commits/with_dockey_test.go
  tests/integration/query/one_to_many/with_cid_dockey_test.go
  tests/integration/query/simple/with_cid_dockey_test.go
  tests/integration/query/simple/with_version_test.go
Labels: feature, area/query, action/no-benchmark

#1456 test: Add tests to assert schema id order independence
  tests/integration/net/state/simple/replicator/with_create_test.go
Labels: area/schema, action/no-benchmark

#1459 fix: Handling SIGTERM in CLI `start` command
  cli/start.go
Labels: area/cli

#1466 fix: Reference collectionID in p2p readme
  README.md
Labels: documentation, area/p2p, action/no-benchmark

#1460 fix: Rename commit field input arg to fieldId
  client/request/commit.go
  client/request/consts.go
  planner/commit.go
  planner/mapper/commitSelect.go
  planner/mapper/mapper.go
  request/graphql/parser/commit.go
  request/graphql/schema/types/commits.go
  request/graphql/schema/types/descriptions.go
  tests/integration/explain/default/dagscan_test.go
  tests/integration/query/commits/with_dockey_field_test.go
  tests/integration/query/commits/with_field_test.go
  tests/integration/query/latest_commits/with_dockey_field_test.go
  tests/integration/query/latest_commits/with_field_test.go
  tests/integration/schema/updates/add/field/create_update_test.go
  tests/integration/schema/updates/move/simple_test.go
Labels: area/query, code quality, action/no-benchmark

#1470 chore: Remove some dead code
  cli/root.go
  tests/integration/utils2.go
Labels: action/no-benchmark

#1461 refactor: Improve rollback on peer P2P collection error
  net/peer.go
Labels: refactor, area/p2p

#1474 test: Convert explain dagscan tests to new explain setup
  tests/integration/explain/default/dagscan_test.go
  tests/integration/explain/default/invalid_type_arg_test.go
  tests/integration/explain/default/with_limit_count_test.go
  tests/integration/explain/default/with_limit_join_test.go
Labels: area/testing, code quality

#1478 test: Convert explain order tests to new explain setup
  tests/integration/explain/default/with_order_join_test.go
  tests/integration/explain/default/with_order_test.go
Labels: area/testing, code quality

#1480 test: Convert explain top-level tests to new explain setup
  tests/integration/explain/default/top_with_average_test.go
  tests/integration/explain/default/top_with_count_test.go
  tests/integration/explain/default/top_with_sum_test.go
Labels: area/testing, code quality

#1482 fix: Add reconnection to known peers
  net/peer.go
Labels: area/p2p

#1491 fix: Make nested joins work correctly from primary direction
  docs/data_format_changes/i1490-no-change-tests-updated.md
  planner/type_join.go
  tests/integration/query/one_to_one_to_many/simple_test.go
  tests/integration/query/one_to_one_to_one/simple_test.go
  tests/integration/query/one_to_one_to_one/utils.go
Labels: bug, area/query, action/no-benchmark

#1487 test: Convert explain average tests to new explain setup
  tests/integration/explain/default/with_average_join_test.go
  tests/integration/explain/default/with_average_test.go
Labels: area/testing, code quality

#1489 test: Convert explain sum tests to new explain setup
  tests/integration/explain/default/with_sum_join_test.go
  tests/integration/explain/default/with_sum_test.go
Labels: area/testing, code quality

#1495 fix: Skip new test packages in change detector
  tests/integration/change_detector.go
Labels: bug, area/testing, action/no-benchmark

#1493 refactor: Use `int32` for proper gql scalar Int parsing
  connor/eq.go
  go.mod
  go.sum
  tests/integration/explain/default/delete_test.go
  tests/integration/explain/default/group_with_dockey_test.go
  tests/integration/explain/default/group_with_filter_test.go
  tests/integration/explain/default/top_with_average_test.go
  tests/integration/explain/default/top_with_count_test.go
  tests/integration/explain/default/top_with_sum_test.go
  tests/integration/explain/default/with_average_join_test.go
  tests/integration/explain/default/with_filter_test.go
Labels: area/query, refactor, action/no-benchmark

#1492 test: Provide tests for client introspection query
  tests/integration/schema/client_introspection/altair_graphiql_postman_2023.gql
  tests/integration/schema/client_introspection/one_many_test.go
  tests/integration/schema/client_introspection/simple_test.go
  tests/integration/test_case.go
  tests/integration/utils2.go
Labels: area/query, area/testing, action/no-benchmark

#1410 chore: Enshrine defra logger names
  api/http/handler_test.go
  api/http/http.go
  api/http/logger_test.go
  cli/cli.go
  cmd/genclidocs/genclidocs.go
  cmd/genmanpages/main.go
  config/config.go
  datastore/store.go
  db/db.go
  logging/logging.go
  merkle/clock/clock.go
  merkle/crdt/merklecrdt.go
  net/api/service.go
  net/net.go
  node/node.go
  planner/planner.go
  tests/bench/bench_util.go
  tests/bench/query/simple/utils.go
  tests/integration/cli/version_test.go
  tests/integration/explain/utils.go
  tests/integration/net/order/utils.go
  tests/integration/utils2.go
Labels: area/logging

#1504 test: Add DB/Node Restart tests
  net/peer.go
  node/node.go
  tests/bench/bench_util.go
  tests/integration/change_detector.go
  tests/integration/explain/utils.go
  tests/integration/net/order/utils.go
  tests/integration/net/state/simple/peer/with_update_restart_test.go
  tests/integration/net/state/simple/peer_replicator/with_update_restart_test.go
  tests/integration/net/state/simple/replicator/with_create_restart_test.go
  tests/integration/p2p.go
  tests/integration/query/simple/with_restart_test.go
  tests/integration/test_case.go
  tests/integration/utils2.go
Labels: area/testing, action/no-benchmark

#1503 feat: CLI client request from file
  cli/request.go
  examples/request/user_creation.graphql
  examples/request/user_query.graphql
  tests/integration/cli/client_query_test.go
Labels: action/no-benchmark, area/cli

#1509 test: Require no errors when none expected
  tests/integration/utils2.go
Labels: area/testing, action/no-benchmark

#1515 test: Resume wait correctly following test node restart
  tests/integration/p2p.go
  tests/integration/utils2.go
Labels: area/testing, action/no-benchmark

#1514 ci: Fix terraform plan and merge AMI build + deploy workflow
  .github/workflows/build-ami-with-packer.yml
  .github/workflows/build-then-deploy-ami.yml
  .github/workflows/deploy-ami-with-terraform.yml
  .github/workflows/preview-ami-with-terraform-plan.yml
Labels: ci/build, code quality

#1521 test: Add tests for foo_id field name clashes
  tests/integration/query/one_to_many/with_id_field_test.go
  tests/integration/query/one_to_one/with_id_field_test.go
Labels: area/testing, action/no-benchmark

#1528 fix: Change `core.DocumentMapping` to pointer
  planner/average.go
  planner/commit.go
  planner/count.go
  planner/create.go
  planner/delete.go
  planner/group.go
  planner/limit.go
  planner/mapper/aggregate.go
  planner/mapper/mapper.go
  planner/mapper/select.go
  planner/order.go
  planner/scan.go
  planner/select.go
  planner/sum.go
  planner/top.go
  planner/update.go
  tests/integration/query/one_to_many_to_one/with_filter_test.go
  tests/integration/utils2.go
Labels: bug, area/mapper

#1531 fix: Document change detector breaking change
  docs/data_format_changes/i1530-change-detector-without-non-mutations.md
  tests/integration/utils2.go
Labels: bug, area/testing

#1538 ci(i): Respect ignore decorator on PR title validation
  tools/scripts/scripts_test.sh
  tools/scripts/validate-conventional-style.sh
Labels: documentation, ci/build

#1541 fix: Filter splitting and rendering for related types
  planner/count.go
  planner/delete.go
  planner/group.go
  planner/mapper/targetable.go
  planner/scan.go
  planner/select.go
  planner/sum.go
  planner/type_join.go
  planner/update.go
  tests/integration/explain/default/type_join_with_filter.go
  tests/integration/query/one_to_many_multiple/with_multiple_filter_test.go
Labels: bug, action/no-benchmark, area/planner

#1543 test(i): Convert simple explain test to new explain setup
  tests/integration/explain/default/basic_test.go
  tests/integration/explain/default/create_test.go
  tests/integration/explain/default/dagscan_test.go
  tests/integration/explain/default/delete_test.go
  tests/integration/explain/default/delete_with_error_test.go
  tests/integration/explain/default/fixture.go
  tests/integration/explain/default/group_test.go
  tests/integration/explain/default/group_with_average_test.go
  tests/integration/explain/default/group_with_dockey_child_test.go
  tests/integration/explain/default/group_with_dockey_test.go
  tests/integration/explain/default/group_with_filter_child_test.go
  tests/integration/explain/default/group_with_filter_test.go
  tests/integration/explain/default/group_with_limit_child_test.go
  tests/integration/explain/default/group_with_limit_test.go
  tests/integration/explain/default/group_with_order_child_test.go
  tests/integration/explain/default/group_with_order_test.go
  tests/integration/explain/default/invalid_type_arg_test.go
  tests/integration/explain/default/top_with_average_test.go
  tests/integration/explain/default/top_with_count_test.go
  tests/integration/explain/default/top_with_sum_test.go
  tests/integration/explain/default/type_join_many_test.go
  tests/integration/explain/default/type_join_one_test.go
  tests/integration/explain/default/type_join_test.go
  tests/integration/explain/default/type_join_with_filter.go
  tests/integration/explain/default/update_test.go
  tests/integration/explain/default/utils.go
  tests/integration/explain/default/with_average_join_test.go
  tests/integration/explain/default/with_average_test.go
  tests/integration/explain/default/with_count_join_test.go
  tests/integration/explain/default/with_count_test.go
  tests/integration/explain/default/with_filter_key_test.go
  tests/integration/explain/default/with_filter_test.go
  tests/integration/explain/default/with_limit_count_test.go
  tests/integration/explain/default/with_limit_join_test.go
  tests/integration/explain/default/with_limit_test.go
  tests/integration/explain/default/with_order_join_test.go
  tests/integration/explain/default/with_order_test.go
  tests/integration/explain/default/with_sum_join_test.go
  tests/integration/explain/default/with_sum_test.go
  tests/integration/explain/fixture.go
  tests/integration/explain/simple/basic_test.go
Labels: area/testing, code quality

#1545 test(i): Integrate explain tests into test action system
  docs/data_format_changes/i1243-enable-previously-skipped-explain-tests.md
  tests/integration/explain.go
  tests/integration/explain/default/basic_test.go
  tests/integration/explain/default/create_test.go
  tests/integration/explain/default/dagscan_test.go
  tests/integration/explain/default/delete_test.go
  tests/integration/explain/default/delete_with_error_test.go
  tests/integration/explain/default/group_test.go
  tests/integration/explain/default/group_with_average_test.go
  tests/integration/explain/default/group_with_dockey_child_test.go
  tests/integration/explain/default/group_with_dockey_test.go
  tests/integration/explain/default/group_with_filter_child_test.go
  tests/integration/explain/default/group_with_filter_test.go
  tests/integration/explain/default/group_with_limit_child_test.go
  tests/integration/explain/default/group_with_limit_test.go
  tests/integration/explain/default/group_with_order_child_test.go
  tests/integration/explain/default/group_with_order_test.go
  tests/integration/explain/default/invalid_type_arg_test.go
  tests/integration/explain/default/top_with_average_test.go
  tests/integration/explain/default/top_with_count_test.go
  tests/integration/explain/default/top_with_sum_test.go
  tests/integration/explain/default/type_join_many_test.go
  tests/integration/explain/default/type_join_one_test.go
  tests/integration/explain/default/type_join_test.go
  tests/integration/explain/default/type_join_with_filter.go
  tests/integration/explain/default/type_join_with_filter_test.go
  tests/integration/explain/default/update_test.go
  tests/integration/explain/default/with_average_join_test.go
  tests/integration/explain/default/with_average_test.go
  tests/integration/explain/default/with_count_join_test.go
  tests/integration/explain/default/with_count_test.go
  tests/integration/explain/default/with_filter_key_test.go
  tests/integration/explain/default/with_filter_test.go
  tests/integration/explain/default/with_limit_count_test.go
  tests/integration/explain/default/with_limit_join_test.go
  tests/integration/explain/default/with_limit_test.go
  tests/integration/explain/default/with_order_join_test.go
  tests/integration/explain/default/with_order_test.go
  tests/integration/explain/default/with_sum_join_test.go
  tests/integration/explain/default/with_sum_test.go
  tests/integration/explain/execute/create_test.go
  tests/integration/explain/execute/dagscan_test.go
  tests/integration/explain/execute/delete_test.go
  tests/integration/explain/execute/fixture.go
  tests/integration/explain/execute/group_test.go
  tests/integration/explain/execute/scan_test.go
  tests/integration/explain/execute/top_level_test.go
  tests/integration/explain/execute/type_join_test.go
  tests/integration/explain/execute/update_test.go
  tests/integration/explain/execute/with_average_test.go
  tests/integration/explain/execute/with_count_test.go
  tests/integration/explain/execute/with_limit_test.go
  tests/integration/explain/execute/with_order_test.go
  tests/integration/explain/execute/with_sum_test.go
  tests/integration/explain/fixture.go
  tests/integration/explain/simple/basic_test.go
  tests/integration/utils2.go
Labels: area/testing, code quality

#1549 ci(i): Cleanup codecov config & enable annotations
  .github/codecov.yml
  .github/workflows/code-test-coverage.yml
  Makefile
Labels: ci/build, config-change
