Repository sourcenetwork/defradb, pull requests merged in 2023-09, with the labels that each got.

#1850 test(i): Skip unsupported mutation types at test level
  tests/integration/collection/update/simple/with_deleted_test.go
  tests/integration/mutation/create/simple_test.go
  tests/integration/mutation/update/field_kinds/array_bool_test.go
  tests/integration/mutation/update/field_kinds/array_float_test.go
  tests/integration/mutation/update/field_kinds/array_int_test.go
  tests/integration/mutation/update/field_kinds/array_string_test.go
  tests/integration/test_case.go
  tests/integration/utils2.go
Labels: bug, area/testing, action/no-benchmark

#1855 fix: Compound filter operators with relations
  client/request/filter.go
  planner/filter/complex.go
  planner/filter/complex_test.go
  planner/filter/copy.go
  planner/filter/copy_field.go
  planner/filter/copy_field_test.go
  planner/filter/copy_test.go
  planner/filter/merge.go
  planner/filter/merge_test.go
  planner/filter/normalize.go
  planner/filter/normalize_test.go
  planner/filter/remove_field.go
  planner/filter/remove_field_test.go
  planner/filter/split.go
  planner/filter/split_test.go
  planner/filter/util_test.go
  planner/mapper/mapper.go
  planner/mapper/targetable.go
  planner/type_join.go
  tests/integration/query/one_to_many/with_filter_test.go
  tests/integration/query/one_to_many_to_one/with_filter_test.go
  tests/integration/query/one_to_one/with_filter_test.go
  tests/integration/query/simple/with_filter/with_not_test.go
Labels: bug, area/query

#1872 fix: Correctly handle serialisation of nil field values
  client/document.go
  client/document_test.go
  tests/integration/mutation/update/field_kinds/array_bool_test.go
  tests/integration/mutation/update/field_kinds/array_float_test.go
  tests/integration/mutation/update/field_kinds/array_int_test.go
  tests/integration/mutation/update/field_kinds/array_string_test.go
Labels: bug, area/collections, action/no-benchmark

#1870 test(i): Test top level agg. wt compound relational filter
  tests/integration/query/one_to_many/with_cid_dockey_test.go
  tests/integration/query/one_to_one/with_count_filter_test.go
  tests/integration/utils2.go
Labels: area/query, area/testing, code quality

#1881 chore: Bump golangci-lint to v1.54
  .github/workflows/lint.yml
  Makefile
  errors/defraError.go
Labels: ci/build, code quality

#1878 test: Convert and move out of place explain tests
  tests/integration/explain/default/with_average_join_test.go
  tests/integration/explain/default/with_count_join_test.go
  tests/integration/explain/fixture.go
  tests/integration/query/one_to_many/utils.go
  tests/integration/query/one_to_many/with_average_filter_test.go
  tests/integration/query/one_to_many/with_count_filter_test.go
Labels: area/testing

#1871 ci: Parallelize change detector
  Makefile
  docs/data_format_changes/i1436-no-change-tests-updated.md
  tests/change_detector/README.md
  tests/change_detector/change_detector_test.go
  tests/change_detector/utils.go
  tests/integration/change_detector.go
  tests/integration/utils2.go
Labels: area/testing

#1896 feat: Add CCIP Support
  http/handler_ccip.go
  http/handler_ccip_test.go
  http/server.go
Labels: feature, area/api

#1912 fix(i): Flaky normalize filter test
  planner/filter/normalize.go
Labels: bug, area/planner

#1915 fix: Infinite loop when updating one-one relation
  client/descriptions.go
  db/collection.go
  db/collection_update.go
  planner/type_join.go
  tests/integration/mutation/update/field_kinds/one_to_one/with_self_ref_test.go
Labels: bug, area/query
