Repository sourcenetwork/defradb, pull requests merged in 2023-07, with the labels that each got.

#1603 test: Rework transaction test framework capabilities
  docs/data_format_changes/i1602-no-change-tests-updated.md
  tests/integration/mutation/relation/create/with_txn_test.go
  tests/integration/mutation/relation/delete/with_txn_test.go
  tests/integration/mutation/simple/delete/multi_ids_test.go
  tests/integration/mutation/simple/delete/single_id_test.go
  tests/integration/mutation/simple/mix/with_txn_test.go
  tests/integration/test_case.go
  tests/integration/utils.go
  tests/integration/utils2.go
Labels: area/testing, refactor, action/no-benchmark

#1608 fix: Change the WriteSyncer to use lock when piping
  logging/logger.go
Labels: bug, area/logging

#1595 feat: CLI commands for secondary indexes
  Makefile
  api/http/handlerfuncs_index.go
  api/http/handlerfuncs_index_test.go
  api/http/router.go
  cli/cli.go
  cli/errors.go
  cli/index.go
  cli/index_create.go
  cli/index_create_test.go
  cli/index_drop.go
  cli/index_drop_test.go
  cli/index_list.go
  cli/index_list_test.go
  client/db.go
  client/mocks/Collection.go
  client/mocks/DB.go
  db/collection_index.go
  db/index_test.go
  db/txn_db.go
  logging/config.go
  logging/logger.go
  logging/logging_test.go
  tests/integration/cli/client_index_create_test.go
  tests/integration/cli/client_index_drop_test.go
  tests/integration/cli/client_index_list_test.go
Labels: area/cli

#1612 ci: Build mocks using make
  Makefile
  client/mocks/Collection.go
  client/mocks/DB.go
  datastore/mocks/DAGStore.go
  datastore/mocks/DSReaderWriter.go
  datastore/mocks/Results.go
  datastore/mocks/RootStore.go
  datastore/mocks/Txn.go
  tests/README.md
Labels: area/testing, refactor

#1593 refactor: Merge `node` into `net` and improve coverage
  cli/start.go
  config/config.go
  config/config_test.go
  go.mod
  go.sum
  net/api/client/client.go
  net/api/pb/Makefile
  net/api/pb/api.pb.go
  net/api/pb/api.proto
  net/api/pb/api_grpc.pb.go
  net/api/pb/api_vtproto.pb.go
  net/api/service.go
  net/client.go
  net/client_test.go
  net/config.go
  net/config_test.go
  net/dag.go
  net/dag_test.go
  net/dialer.go
  net/dialer_test.go
  net/errors.go
  net/node.go
  net/node_test.go
  net/pb/Makefile
  net/pb/custom.go
  net/pb/net.pb.go
  net/pb/net.proto
  net/pb/net_grpc.pb.go
  net/pb/net_vtproto.pb.go
  net/peer.go
  net/peer_test.go
  net/process.go
  net/server.go
  net/server_test.go
  node/node_test.go
  tests/integration/net/order/utils.go
  tests/integration/p2p.go
  tests/integration/utils2.go
Labels: refactor, area/network

#1621 fix: Avoid duplicated requestable fields
  planner/mapper/mapper.go
Labels: bug, area/mapper

#1625 feat: Schema list API
  api/http/handlerfuncs.go
  api/http/handlerfuncs_test.go
  api/http/router.go
  cli/cli.go
  cli/schema_add.go
  cli/schema_list.go
  cli/schema_patch.go
  client/descriptions.go
Labels: feature, area/api

#1564 feat: Add lens migration engine to defra
  .gitignore
  CONTRIBUTING.md
  Makefile
  client/db.go
  client/document.go
  client/lens.go
  client/mocks/DB.go
  core/crdt/composite.go
  core/doc.go
  core/encoding.go
  core/key.go
  db/collection.go
  db/collection_get.go
  db/collection_index.go
  db/db.go
  db/fetcher/encoded_doc.go
  db/fetcher/fetcher.go
  db/fetcher/mocks/EncodedDocument.go
  db/fetcher/mocks/Fetcher.go
  db/fetcher/mocks/utils.go
  db/fetcher/versioned.go
  db/fetcher_test.go
  db/indexed_docs_test.go
  db/txn_db.go
  docs/data_format_changes/i1448-migration-engine.md
  go.mod
  go.sum
  lens/fetcher.go
  lens/history.go
  lens/lens.go
  lens/registry.go
  planner/mapper/mapper.go
  planner/order.go
  planner/scan.go
  tests/integration/lens.go
  tests/integration/schema/migrations/query/simple_test.go
  tests/integration/schema/migrations/query/with_dockey_test.go
  tests/integration/schema/migrations/query/with_p2p_test.go
  tests/integration/schema/migrations/query/with_restart_test.go
  tests/integration/schema/migrations/query/with_txn_test.go
  tests/integration/schema/migrations/query/with_update_test.go
  tests/integration/schema/migrations/simple_test.go
  tests/integration/schema/migrations/with_txn_test.go
  tests/integration/utils2.go
  tests/lenses/LICENSE
  tests/lenses/Makefile
  tests/lenses/rust_wasm32_copy/Cargo.toml
  tests/lenses/rust_wasm32_copy/src/lib.rs
  tests/lenses/rust_wasm32_remove/Cargo.toml
  tests/lenses/rust_wasm32_remove/src/lib.rs
  tests/lenses/rust_wasm32_set_default/Cargo.toml
  tests/lenses/rust_wasm32_set_default/src/lib.rs
  tests/lenses/utils.go
  tests/lenses/verified_true.json
Labels: feature, area/schema, action/no-benchmark

#1631 feat: Add `_not` operator
  connor/connor.go
  connor/not.go
  connor/not_test.go
  planner/mapper/mapper.go
  planner/mapper/targetable.go
  tests/integration/query/simple/with_filter/with_not_test.go
Labels: feature, area/query, area/mapper

#1633 fix: Introspection OrderArg returns null inputFields
  request/graphql/schema/generate.go
  tests/integration/explain/debug/with_order_join_test.go
  tests/integration/explain/default/with_order_join_test.go
  tests/integration/explain/execute/with_order_test.go
  tests/integration/schema/default_fields.go
  tests/integration/schema/input_type_test.go
Labels: bug

#1635 refactor: Remove redundant txn param from fetcher start
  db/collection_get.go
  db/collection_index.go
  db/fetcher/fetcher.go
  db/fetcher/mocks/Fetcher.go
  db/fetcher/mocks/utils.go
  db/fetcher/versioned.go
  db/fetcher_test.go
  db/indexed_docs_test.go
  lens/fetcher.go
  planner/scan.go
Labels: area/db-system, refactor, code quality, action/no-benchmark

#1645 test: Bundle test state into single var
  tests/integration/explain.go
  tests/integration/lens.go
  tests/integration/p2p.go
  tests/integration/state.go
  tests/integration/test_case.go
  tests/integration/utils2.go
Labels: area/testing, code quality, action/no-benchmark

#1643 test: Remove CLI tests from make test
  Makefile
Labels: code quality, action/no-benchmark, area/cli

#1650 feat: Add schema migration get and set cmds to CLI
  api/http/handlerfuncs.go
  api/http/router.go
  cli/cli.go
  cli/schema_migration.go
  cli/schema_migration_get.go
  cli/schema_migration_set.go
Labels: feature, area/schema, area/api, action/no-benchmark, area/cli

#1575 feat: Playground
  Makefile
  api/http/handler.go
  api/http/handlerfuncs.go
  api/http/handlerfuncs_test.go
  api/http/logger_test.go
  api/http/playground.go
  api/http/router.go
  cli/schema_list.go
  client/descriptions.go
  playground/.gitignore
  playground/README.md
  playground/index.html
  playground/package-lock.json
  playground/package.json
  playground/playground.go
  playground/src/App.tsx
  playground/src/components/Plugin.tsx
  playground/src/components/SchemaLoadForm.tsx
  playground/src/components/SchemaPatchForm.tsx
  playground/src/index.css
  playground/src/lib/api.ts
  playground/src/main.tsx
  playground/src/vite-env.d.ts
  playground/tsconfig.json
  playground/tsconfig.node.json
  playground/vite.config.ts
Labels: feature, area/api

#1415 fix: Better wait in CLI integration test
  tests/integration/cli/utils.go
Labels: area/testing

#1665 fix(i): Add config for Dependabot NPM
  .github/dependabot.yml
Labels: ci/build

#1647 fix: Return error when relation is not defined on both types
  request/graphql/schema/collection.go
  request/graphql/schema/errors.go
  tests/integration/schema/relations_test.go
  tests/integration/schema/simple_test.go
Labels: bug, area/schema

#1675 test: Disable test
  tests/integration/query/one_to_one/with_group_related_id_test.go
Labels: bug, area/testing, action/no-benchmark

#1641 refactor: Reuse lens wasm modules
  go.mod
  go.sum
  lens/registry.go
  tests/integration/utils2.go
Labels: area/schema, perf, action/no-benchmark

#1505 docs: Improve CLI command documentation
  README.md
  cli/blocks_get.go
  cli/client.go
  cli/dump.go
  cli/errors.go
  cli/init.go
  cli/p2p_collection.go
  cli/p2p_collection_add.go
  cli/p2p_collection_getall.go
  cli/p2p_collection_remove.go
  cli/peerid.go
  cli/ping.go
  cli/replicator.go
  cli/replicator_delete.go
  cli/replicator_getall.go
  cli/replicator_set.go
  cli/root.go
  cli/rpc.go
  cli/schema.go
  cli/schema_add.go
  cli/schema_patch.go
  cli/start.go
  core/net/protocol.go
  docs/cli/defradb.md
  docs/cli/defradb_client.md
  docs/cli/defradb_client_blocks.md
  docs/cli/defradb_client_blocks_get.md
  docs/cli/defradb_client_dump.md
  docs/cli/defradb_client_peerid.md
  docs/cli/defradb_client_ping.md
  docs/cli/defradb_client_query.md
  docs/cli/defradb_client_rpc.md
  docs/cli/defradb_client_rpc_addreplicator.md
  docs/cli/defradb_client_rpc_p2pcollection.md
  docs/cli/defradb_client_rpc_p2pcollection_add.md
  docs/cli/defradb_client_rpc_p2pcollection_getall.md
  docs/cli/defradb_client_rpc_p2pcollection_remove.md
  docs/cli/defradb_client_rpc_replicator.md
  docs/cli/defradb_client_rpc_replicator_delete.md
  docs/cli/defradb_client_rpc_replicator_getall.md
  docs/cli/defradb_client_rpc_replicator_set.md
  docs/cli/defradb_client_schema.md
  docs/cli/defradb_client_schema_add.md
  docs/cli/defradb_client_schema_patch.md
  docs/cli/defradb_init.md
  docs/cli/defradb_start.md
  net/client.go
  net/dag.go
  net/doc.go
  net/peer.go
  tests/integration/net/order/utils.go
Labels: action/no-benchmark, area/cli

#1677 chore(i): Update javascript packages
  playground/package-lock.json
  playground/package.json
Labels: dependencies, javascript

#1678 fix: Remove duplicated `peers` in peerstore prefix
  net/node.go
Labels: area/p2p

#1682 fix: Standardise `schema migration` CLI errors
  Makefile
  cli/errors.go
  cli/schema_migration_get.go
  cli/schema_migration_set.go
  cli/schema_patch.go
  tests/integration/cli/client_schema_migration_get_test.go
  tests/integration/cli/client_schema_migration_set_test.go
Labels: code quality, action/no-benchmark, area/cli

#1685 fix: Fix invalid (badger) datastore state
  db/fetcher/encoded_doc.go
  db/fetcher/fetcher.go
  planner/scan.go
  tests/integration/query/one_to_one/with_group_related_id_test.go
Labels: bug, area/db-system, action/no-benchmark

#1630 feat: Add simple data import and export
  README.md
  api/http/errors.go
  api/http/handlerfuncs.go
  api/http/handlerfuncs_backup.go
  api/http/handlerfuncs_backup_test.go
  api/http/handlerfuncs_test.go
  api/http/router.go
  cli/backup.go
  cli/backup_export.go
  cli/backup_export_test.go
  cli/backup_import.go
  cli/backup_import_test.go
  cli/cli.go
  cli/dump.go
  cli/errors.go
  cli/index_create.go
  cli/index_create_test.go
  cli/index_drop.go
  cli/index_drop_test.go
  cli/index_list.go
  cli/index_list_test.go
  cli/peerid.go
  cli/ping.go
  cli/request.go
  cli/schema_add.go
  cli/schema_migration_get.go
  cli/schema_migration_set.go
  client/backup.go
  client/db.go
  client/mocks/DB.go
  db/backup.go
  db/backup_test.go
  db/errors.go
  db/txn_db.go
  request/graphql/schema/collection.go
  tests/integration/backup/one_to_many/export_test.go
  tests/integration/backup/one_to_many/import_test.go
  tests/integration/backup/one_to_many/utils.go
  tests/integration/backup/one_to_one/export_test.go
  tests/integration/backup/one_to_one/import_test.go
  tests/integration/backup/one_to_one/utils.go
  tests/integration/backup/self_reference/export_test.go
  tests/integration/backup/self_reference/utils.go
  tests/integration/backup/simple/export_test.go
  tests/integration/backup/simple/import_test.go
  tests/integration/backup/simple/utils.go
  tests/integration/cli/client_backup_export_test.go
  tests/integration/cli/client_backup_import_test.go
  tests/integration/cli/utils.go
  tests/integration/test_case.go
  tests/integration/utils2.go
Labels: feature, area/api, area/cli

#1699 test: Expand backup integration tests
  tests/integration/backup/one_to_one/import_test.go
  tests/integration/backup/self_reference/import_test.go
  tests/integration/backup/self_reference/utils.go
  tests/integration/backup/simple/export_test.go
  tests/integration/backup/simple/import_test.go
Labels: area/db-system, area/testing, code quality, action/no-benchmark

#1706 refactor: Schema list output to include schemaVersionID
  api/http/handlerfuncs.go
  api/http/handlerfuncs_test.go
  cli/schema_list.go
  tests/integration/cli/client_schema_add_test.go
Labels: area/api, refactor, area/cli

#1676 ci: Add workflows to push, pull, and validate docker images
  .github/workflows/pull-docker-image.yml
  .github/workflows/push-docker-image-to-registries.yml
  .github/workflows/validate-containerfile.yml
  tools/defradb.containerfile
Labels: ci/build

#1701 fix(i): Add self reference import handling
  db/backup.go
  db/errors.go
  request/graphql/schema/collection.go
  tests/integration/backup/one_to_one/import_test.go
  tests/integration/backup/self_reference/import_test.go
  tests/integration/schema/relations_test.go
Labels: bug

#1716 fix: Return errors from typeJoinOne
  planner/errors.go
  planner/planner.go
  planner/type_join.go
Labels: bug, area/query, action/no-benchmark

#1715 fix: Discard index and subscription implicit transactions
  db/collection_index.go
  db/subscriptions.go
Labels: bug, area/datastore

#1723 feat(i): Switch migrations to use wazero runtime
  Makefile
  go.mod
  go.sum
  lens/registry.go
Labels: feature, area/schema, action/no-benchmark

#1729 tools(i): Fix the broken containerfile due to libwasmer
  .github/workflows/validate-containerfile.yml
  tests/lenses/rust_wasm32_copy/Cargo.toml
  tests/lenses/rust_wasm32_remove/Cargo.toml
  tests/lenses/rust_wasm32_set_default/Cargo.toml
  tools/defradb-builder.containerfile
  tools/defradb.containerfile
Labels: ci/build, code quality, dependencies
