Repository sourcenetwork/defradb, pull requests merged in 2024-04, with the labels that each got.

#2495 test: Add flag to skip network tests
  tests/integration/utils2.go
Labels: area/testing

#2497 feat: Lens runtime config
  db/config.go
  db/config_test.go
  db/db.go
  lens/registry.go
Labels: feature

#2513 refactor: DB transactions context
  cli/client.go
  cli/collection.go
  cli/index_create.go
  cli/index_drop.go
  cli/index_list.go
  cli/schema_migration_down.go
  cli/schema_migration_reload.go
  cli/schema_migration_up.go
  cli/utils.go
  client/collection.go
  client/db.go
  client/lens.go
  db/backup.go
  db/collection.go
  db/collection_delete.go
  db/collection_get.go
  db/collection_index.go
  db/collection_update.go
  db/context.go
  db/context_test.go
  db/db.go
  db/db_test.go
  db/index_test.go
  db/indexed_docs_test.go
  db/request.go
  db/store.go
  db/subscriptions.go
  db/txn_db.go
  http/client.go
  http/client_collection.go
  http/client_lens.go
  http/handler.go
  http/handler_ccip.go
  http/handler_collection.go
  http/handler_lens.go
  http/handler_store.go
  http/http_client.go
  http/middleware.go
  net/peer_collection.go
  net/peer_replicator.go
  net/server.go
  planner/create.go
  planner/delete.go
  planner/update.go
  tests/bench/query/planner/utils.go
  tests/clients/cli/wrapper.go
  tests/clients/cli/wrapper_cli.go
  tests/clients/cli/wrapper_collection.go
  tests/clients/cli/wrapper_lens.go
  tests/clients/http/wrapper.go
  tests/integration/events/simple/with_create_txn_test.go
  tests/integration/lens.go
  tests/integration/utils2.go
Labels: area/db-system

#2518 refactor(i): Remove datastore.Txn from private db methods
  db/backup.go
  db/backup_test.go
  db/collection.go
  db/collection_delete.go
  db/collection_get.go
  db/collection_index.go
  db/collection_update.go
  db/context.go
  db/db.go
  db/index_test.go
  db/indexed_docs_test.go
  db/lens.go
  db/request.go
  db/schema.go
  db/sequence.go
  db/store.go
  db/subscriptions.go
  db/view.go
Labels: area/db-system

#2511 fix: Allow update when updating non-indexed field
  db/index.go
  tests/integration/index/update_unique_composite_test.go
  tests/integration/index/update_unique_test.go
Labels: bug

#2535 test(i): Assert all expected props are returned in tests
  tests/integration/backup/one_to_one/import_test.go
  tests/integration/net/state/simple/peer/with_create_add_field_test.go
  tests/integration/query/one_to_many/with_cid_doc_id_test.go
  tests/integration/query/one_to_many/with_group_related_id_alias_test.go
  tests/integration/query/one_to_many/with_group_related_id_test.go
  tests/integration/query/simple/with_order_test.go
  tests/integration/schema/migrations/query/with_p2p_schema_branch_test.go
  tests/integration/utils2.go
  tests/integration/view/simple/with_filter_test.go
Labels: bug, area/testing

#2534 fix: Make all array kinds nillable
  client/normal_nil.go
  client/normal_value_test.go
  client/schema_field_description.go
Labels: bug

#2531 refactor: Merge collection UpdateWith and DeleteWith
  cli/collection_delete.go
  cli/collection_update.go
  client/collection.go
  client/document.go
  db/collection_delete.go
  db/collection_update.go
  docs/cli/defradb_client_collection_delete.md
  docs/cli/defradb_client_collection_update.md
  http/client_collection.go
  http/handler_collection.go
  planner/delete.go
  planner/update.go
  tests/clients/cli/wrapper_collection.go
  tests/integration/collection/update/simple/with_doc_id_test.go
  tests/integration/collection/update/simple/with_doc_ids_test.go
  tests/integration/utils2.go
Labels: area/api

#2544 docs: Add data definition document
  client/README.md
  client/data_definition.md
Labels: documentation, area/schema, area/collections

#2547 feat: Update corelog to 0.0.7
  cli/config.go
  cli/config_test.go
  cli/root.go
  docs/config.md
  go.mod
  go.sum
Labels: feature

#2567 test(i): Fix PnCounter overflow tests
  tests/integration/issues/2566_test.go
  tests/integration/issues/2569_test.go
  tests/integration/issues/README.md
  tests/integration/mutation/update/crdt/pncounter_test.go
  tests/integration/test_case.go
  tests/integration/utils2.go
Labels: area/testing, code quality
