Repository sourcenetwork/defradb, pull requests merged in 2024-07, with the labels that each got.

#2768 refactor: Decouple client.DB from net
  client/db.go
  client/errors.go
  client/mocks/db.go
  client/p2p.go
  datastore/blockstore.go
  datastore/mocks/root_store.go
  datastore/mocks/txn.go
  datastore/mocks/utils.go
  datastore/multi.go
  datastore/store.go
  event/event.go
  go.mod
  http/client.go
  http/client_tx.go
  internal/db/db.go
  internal/db/errors.go
  internal/db/fetcher/versioned.go
  internal/db/index_test.go
  internal/db/merge.go
  internal/db/merge_test.go
  internal/db/messages.go
  internal/db/p2p_replicator.go
  internal/db/p2p_replicator_test.go
  internal/db/p2p_schema_root.go
  internal/db/p2p_schema_root_test.go
  internal/merkle/clock/clock.go
  internal/merkle/clock/clock_test.go
  internal/merkle/crdt/composite.go
  internal/merkle/crdt/counter.go
  internal/merkle/crdt/lwwreg.go
  internal/merkle/crdt/merklecrdt.go
  internal/merkle/crdt/merklecrdt_test.go
  internal/planner/commit.go
  net/client_test.go
  net/dialer_test.go
  net/errors.go
  net/node.go
  net/node_test.go
  net/peer.go
  net/peer_replicator.go
  net/peer_test.go
  net/server.go
  net/server_test.go
  node/node.go
  node/store.go
  tests/bench/bench_util.go
  tests/bench/query/planner/utils.go
  tests/bench/storage/utils.go
  tests/clients/cli/wrapper.go
  tests/clients/cli/wrapper_tx.go
  tests/clients/clients.go
  tests/clients/http/wrapper.go
  tests/clients/http/wrapper_tx.go
  tests/integration/client.go
  tests/integration/db.go
  tests/integration/p2p.go
  tests/integration/utils2.go
Labels: refactor, area/p2p, area/network

#2819 fix: Allow querying of 9th, 19th, 29th, etc collections
  docs/data_format_changes/i2810-allow-query-of-nth-cols.md
  internal/core/data_test.go
  internal/core/encoding.go
  internal/core/key.go
  internal/core/key_test.go
  internal/db/indexed_docs_test.go
  internal/planner/scan.go
  tests/integration/query/simple/with_multiple_types_test.go
  tests/integration/utils2.go
Labels: bug, area/datastore

#2822 test: Remove hardcoded test identities
  docs/data_format_changes/i2821-no-change-tests-updated.md
  tests/integration/acp.go
  tests/integration/acp/add_policy/basic_test.go
  tests/integration/acp/add_policy/fixture.go
  tests/integration/acp/add_policy/with_empty_args_test.go
  tests/integration/acp/add_policy/with_extra_perms_and_relations_test.go
  tests/integration/acp/add_policy/with_extra_perms_test.go
  tests/integration/acp/add_policy/with_extra_relations_test.go
  tests/integration/acp/add_policy/with_invalid_creator_arg_test.go
  tests/integration/acp/add_policy/with_invalid_relations_test.go
  tests/integration/acp/add_policy/with_invalid_required_relation_test.go
  tests/integration/acp/add_policy/with_invalid_resource_test.go
  tests/integration/acp/add_policy/with_managed_relation_test.go
  tests/integration/acp/add_policy/with_multi_policies_test.go
  tests/integration/acp/add_policy/with_multiple_resources_test.go
  tests/integration/acp/add_policy/with_no_perms_test.go
  tests/integration/acp/add_policy/with_no_resources_test.go
  tests/integration/acp/add_policy/with_perm_expr_test.go
  tests/integration/acp/add_policy/with_perm_invalid_expr_test.go
  tests/integration/acp/add_policy/with_permissionless_owner_test.go
  tests/integration/acp/add_policy/with_unused_relations_test.go
  tests/integration/acp/fixture.go
  tests/integration/acp/index/create_test.go
  tests/integration/acp/index/query_test.go
  tests/integration/acp/index/query_with_relation_test.go
  tests/integration/acp/p2p/replicator_test.go
  tests/integration/acp/p2p/subscribe_test.go
  tests/integration/acp/query/avg_test.go
  tests/integration/acp/query/count_test.go
  tests/integration/acp/query/fixture.go
  tests/integration/acp/query/relation_objects_test.go
  tests/integration/acp/register_and_delete_test.go
  tests/integration/acp/register_and_read_test.go
  tests/integration/acp/register_and_update_test.go
  tests/integration/acp/schema/add_dpi/accept_basic_dpi_fmts_test.go
  tests/integration/acp/schema/add_dpi/accept_extra_permissions_on_dpi_test.go
  tests/integration/acp/schema/add_dpi/accept_managed_relation_on_dpi_test.go
  tests/integration/acp/schema/add_dpi/accept_mixed_resources_on_partial_dpi_test.go
  tests/integration/acp/schema/add_dpi/accept_multi_dpis_test.go
  tests/integration/acp/schema/add_dpi/accept_multi_resources_on_dpi_test.go
  tests/integration/acp/schema/add_dpi/accept_same_resource_on_diff_schemas_test.go
  tests/integration/acp/schema/add_dpi/fixture.go
  tests/integration/acp/schema/add_dpi/reject_empty_arg_on_schema_test.go
  tests/integration/acp/schema/add_dpi/reject_invalid_arg_type_on_schema_test.go
  tests/integration/acp/schema/add_dpi/reject_invalid_owner_read_perm_on_dpi_test.go
  tests/integration/acp/schema/add_dpi/reject_invalid_owner_read_perm_symbol_on_dpi_test.go
  tests/integration/acp/schema/add_dpi/reject_invalid_owner_write_perm_on_dpi_test.go
  tests/integration/acp/schema/add_dpi/reject_invalid_owner_write_perm_symbol_on_dpi_test.go
  tests/integration/acp/schema/add_dpi/reject_missing_dpi_test.go
  tests/integration/acp/schema/add_dpi/reject_missing_id_arg_on_schema_test.go
  tests/integration/acp/schema/add_dpi/reject_missing_perms_on_dpi_test.go
  tests/integration/acp/schema/add_dpi/reject_missing_resource_arg_on_schema_test.go
  tests/integration/acp/schema/add_dpi/reject_missing_resource_on_dpi_test.go
  tests/integration/acp/schema/add_dpi/reject_mixed_resources_on_partial_dpi_test.go
  tests/integration/collection_description/updates/remove/policy_test.go
  tests/integration/state.go
  tests/integration/test_case.go
  tests/integration/utils2.go
Labels: area/auth, area/testing, code quality

#2832 test: Fix refreshing of docs in change detector
  tests/integration/utils2.go
Labels: bug, area/testing, priority/high

#2828 fix(i): Make badger dependency optional
  cli/server_dump.go
  cli/start.go
  datastore/badger/v4/datastore.go
  datastore/badger/v4/errors.go
  datastore/blockstore_test.go
  datastore/concurrent_txt_test.go
  datastore/errors.go
  datastore/errors/errors.go
  datastore/memory/errors.go
  datastore/txn_test.go
  datastore/wrappedstore_test.go
  http/utils.go
  internal/db/messages.go
  node/errors.go
  node/store.go
  node/store_badger.go
  node/store_badger_test.go
  node/store_memory.go
  node/store_test.go
  tests/integration/db.go
  tests/integration/mutation/mix/with_txn_test.go
  tests/integration/utils2.go
Labels: area/datastore

#2824 chore: Bump grpc version
  go.mod
  go.sum
Labels: bump

#2841 fix: Enable filtering doc by fields of JSON and Blob types
  internal/request/graphql/schema/manager.go
  internal/request/graphql/schema/types/base.go
  tests/integration/query/simple/with_filter/with_eq_blob_test.go
  tests/integration/query/simple/with_filter/with_eq_json_test.go
  tests/integration/query/simple/with_filter/with_in_blob_test.go
  tests/integration/query/simple/with_filter/with_in_json_test.go
  tests/integration/query/simple/with_filter/with_like_blob_test.go
  tests/integration/query/simple/with_filter/with_like_json_test.go
Labels: area/query

#2748 refactor: Network test sync logic
  net/peer.go
  net/server.go
  tests/integration/acp/register_and_update_test.go
  tests/integration/events.go
  tests/integration/net/simple/peer/with_delete_test.go
  tests/integration/net/simple/replicator/with_create_test.go
  tests/integration/p2p.go
  tests/integration/state.go
  tests/integration/test_case.go
  tests/integration/utils2.go
Labels: area/testing

#2848 feat: Handle P2P with SourceHub ACP
  acp/README.md
  acp/acp.go
  acp/source_hub_client.go
  internal/db/errors.go
  internal/db/p2p_replicator.go
  internal/db/p2p_schema_root.go
  internal/db/p2p_schema_root_test.go
  tests/integration/acp.go
  tests/integration/acp/p2p/replicator_test.go
  tests/integration/acp/p2p/subscribe_test.go
  tests/integration/db.go
  tests/integration/state.go
Labels: feature, area/auth

#2859 feat: Remove IsObjectArray
  client/document.go
  client/schema_field_description.go
  internal/db/collection.go
  internal/db/definition_validation.go
  internal/planner/mapper/mapper.go
  internal/planner/type_join.go
  internal/request/graphql/schema/collection.go
  internal/request/graphql/schema/generate.go
Labels: feature, area/schema, code quality

#2850 fix(i): Tests with primary doc patch update events
  client/definitions.go
  internal/db/collection.go
  internal/db/collection_update.go
  tests/integration/events.go
  tests/integration/events/simple/utils.go
  tests/integration/events/simple/with_create_test.go
  tests/integration/events/simple/with_create_txn_test.go
  tests/integration/events/simple/with_delete_test.go
  tests/integration/events/simple/with_update_test.go
  tests/integration/events/utils.go
  tests/integration/state.go
  tests/integration/utils2.go
Labels: bug, area/testing

#2866 fix(i): Lock sourcehub version
  .github/workflows/test-and-upload-coverage.yml
Labels: ci/build

#2867 fix: Handle multiple child index joins
  internal/db/fetcher/indexer.go
  tests/integration/index/query_with_relation_filter_test.go
Labels: bug, area/query

#2871 test: Add assert on DocIndex for child documents
  tests/integration/index/query_with_relation_filter_test.go
  tests/integration/query/one_to_many_to_many/joins_test.go
  tests/integration/utils2.go
Labels: area/testing

#2861 refactor(i): Collection tests
  cli/collection_update.go
  tests/integration/collection/update/simple/utils.go
  tests/integration/collection/update/simple/with_filter_test.go
  tests/integration/collection/utils.go
  tests/integration/events.go
  tests/integration/test_case.go
  tests/integration/utils2.go
Labels: area/testing

#2874 refactor(i): Subscription test results
  tests/integration/subscription/subscription_test.go
  tests/integration/test_case.go
  tests/integration/utils2.go
Labels: area/testing

#2881 fix: Create mutation introspection
  internal/request/graphql/schema/descriptions.go
  internal/request/graphql/schema/generate.go
Labels: area/query
