Repository sourcenetwork/defradb, pull requests merged in 2024-12, with the labels that each got.

#3293 feat: Aggregate order alias targeting
  internal/db/base/compare.go
  tests/integration/query/one_to_many/with_count_order_test.go
  tests/integration/query/one_to_many/with_sum_order_test.go
Labels: feature

#3252 feat: Aggregate filter alias targeting
  internal/planner/average.go
  internal/planner/count.go
  internal/planner/max.go
  internal/planner/min.go
  internal/planner/select.go
  internal/planner/sum.go
  internal/planner/top.go
  tests/integration/query/one_to_many/with_count_test.go
  tests/integration/query/simple/with_group_aggregate_alias_filter_test.go
Labels: feature

#3292 fix: Add support for operationName and variables in HTTP GET
  http/handler_ccip_test.go
  http/handler_store.go
  http/handler_store_test.go
Labels: bug

#3278 fix: Make requests with no identity work with "*" target
  acp/README.md
  internal/db/permission/check.go
  tests/integration/acp/relationship/doc_actor/add/with_manager_gql_test.go
  tests/integration/acp/relationship/doc_actor/add/with_manager_test.go
  tests/integration/acp/relationship/doc_actor/add/with_only_write_gql_test.go
  tests/integration/acp/relationship/doc_actor/add/with_only_write_test.go
  tests/integration/acp/relationship/doc_actor/add/with_reader_gql_test.go
  tests/integration/acp/relationship/doc_actor/add/with_reader_test.go
  tests/integration/acp/relationship/doc_actor/add/with_target_all_actors_gql_test.go
  tests/integration/acp/relationship/doc_actor/add/with_target_all_actors_test.go
  tests/integration/acp/relationship/doc_actor/add/with_update_gql_test.go
  tests/integration/acp/relationship/doc_actor/add/with_update_test.go
  tests/integration/acp/relationship/doc_actor/delete/with_target_all_actors_test.go
Labels: bug, area/acp

#3268 fix: Adjust OpenAPI index POST example request body
  cli/index_create.go
  client/collection.go
  client/index.go
  client/mocks/collection.go
  docs/website/references/http/openapi.json
  http/client_collection.go
  http/handler_collection.go
  http/openapi.go
  internal/db/collection_define.go
  internal/db/collection_index.go
  internal/db/index_test.go
  internal/db/indexed_docs_test.go
  tests/clients/cli/wrapper_collection.go
  tests/integration/utils.go
Labels: invalid

#3295 feat: Error if purge request made with dev mode disabled
  cli/start.go
  http/errors.go
  http/handler.go
  http/handler_extras.go
  http/handler_extras_test.go
Labels: area/cli

#3316 fix(i): Aggregate filter returns one result
  internal/planner/average.go
  internal/planner/count.go
  internal/planner/max.go
  internal/planner/min.go
  internal/planner/sum.go
  tests/integration/query/one_to_many/with_average_test.go
  tests/integration/query/one_to_many/with_count_test.go
  tests/integration/query/one_to_many/with_max_test.go
  tests/integration/query/one_to_many/with_min_test.go
  tests/integration/query/one_to_many/with_sum_test.go
Labels: bug

#3279 refactor(i): Rewrite document fetcher
  internal/db/collection.go
  internal/db/collection_get.go
  internal/db/collection_index.go
  internal/db/fetcher/document.go
  internal/db/fetcher/fetcher.go
  internal/db/fetcher/filtered.go
  internal/db/fetcher/indexer.go
  internal/db/fetcher/mocks/fetcher.go
  internal/db/fetcher/mocks/utils.go
  internal/db/fetcher/multi.go
  internal/db/fetcher/permissioned.go
  internal/db/fetcher/prefix.go
  internal/db/fetcher/versioned.go
  internal/db/fetcher/wrapper.go
  internal/db/fetcher_test.go
  internal/db/indexed_docs_test.go
  internal/lens/fetcher.go
  internal/planner/scan.go
  tests/integration/explain/execute/update_test.go
  tests/integration/explain/execute/upsert_test.go
  tests/integration/explain/execute/with_limit_test.go
  tests/integration/explain/execute/with_max_test.go
  tests/integration/explain/execute/with_min_test.go
  tests/integration/explain/execute/with_order_test.go
  tests/integration/explain/execute/with_sum_test.go
  tests/integration/index/query_with_composite_index_only_filter_test.go
  tests/integration/index/query_with_relation_filter_test.go
  tests/integration/index/query_with_unique_composite_index_filter_test.go
Labels: area/query, refactor, code quality
