Repository sourcenetwork/defradb, pull requests merged in 2024-10, with the labels that each got.

#3078 feat: Min and max numerical aggregates
  client/request/consts.go
  internal/planner/aggregate.go
  internal/planner/explain.go
  internal/planner/max.go
  internal/planner/min.go
  internal/planner/operations.go
  internal/planner/select.go
  internal/planner/sum.go
  internal/planner/top.go
  internal/request/graphql/schema/generate.go
  internal/request/graphql/schema/types/descriptions.go
  tests/integration/explain.go
  tests/integration/explain/debug/top_with_max_test.go
  tests/integration/explain/debug/top_with_min_test.go
  tests/integration/explain/debug/with_max_join_test.go
  tests/integration/explain/debug/with_max_test.go
  tests/integration/explain/debug/with_min_join_test.go
  tests/integration/explain/debug/with_min_test.go
  tests/integration/explain/default/top_with_max_test.go
  tests/integration/explain/default/top_with_min_test.go
  tests/integration/explain/default/with_max_join_test.go
  tests/integration/explain/default/with_max_test.go
  tests/integration/explain/default/with_min_join_test.go
  tests/integration/explain/default/with_min_test.go
  tests/integration/explain/execute/with_max_test.go
  tests/integration/explain/execute/with_min_test.go
  tests/integration/query/inline_array/with_max_doc_id_test.go
  tests/integration/query/inline_array/with_max_filter_test.go
  tests/integration/query/inline_array/with_max_limit_offset_order_test.go
  tests/integration/query/inline_array/with_max_limit_offset_test.go
  tests/integration/query/inline_array/with_max_test.go
  tests/integration/query/inline_array/with_min_doc_id_test.go
  tests/integration/query/inline_array/with_min_filter_test.go
  tests/integration/query/inline_array/with_min_limit_offset_order_test.go
  tests/integration/query/inline_array/with_min_limit_offset_test.go
  tests/integration/query/inline_array/with_min_test.go
  tests/integration/query/simple/utils.go
  tests/integration/query/simple/with_group_average_max_test.go
  tests/integration/query/simple/with_group_average_min_test.go
  tests/integration/query/simple/with_group_count_max_test.go
  tests/integration/query/simple/with_group_count_min_test.go
  tests/integration/query/simple/with_group_max_filter_test.go
  tests/integration/query/simple/with_group_max_limit_offset_test.go
  tests/integration/query/simple/with_group_max_limit_test.go
  tests/integration/query/simple/with_group_max_test.go
  tests/integration/query/simple/with_group_min_filter_test.go
  tests/integration/query/simple/with_group_min_limit_offset_test.go
  tests/integration/query/simple/with_group_min_limit_test.go
  tests/integration/query/simple/with_group_min_test.go
  tests/integration/query/simple/with_max_filter_test.go
  tests/integration/query/simple/with_max_test.go
  tests/integration/query/simple/with_min_filter_test.go
  tests/integration/query/simple/with_min_test.go
  tests/integration/schema/default_fields.go
Labels: feature, area/query

#3101 fix: Treat explicitly set nil values like omitted values
  client/document.go
  internal/core/crdt/lwwreg.go
  internal/db/collection.go
  tests/integration/events.go
  tests/integration/mutation/create/field_kinds/one_to_one/with_null_value_test.go
  tests/integration/mutation/create/with_null_value_test.go
Labels: bug, area/collections

#3092 feat: Enable Indexing of array fields
  client/index.go
  client/normal_array.go
  client/normal_array_of_nillables.go
  client/normal_nillable_array.go
  client/normal_nillable_array_of_nillables.go
  client/normal_nillable_scalar.go
  client/normal_scalar.go
  client/normal_value.go
  client/normal_value_test.go
  client/normal_void.go
  client/schema_field_description.go
  client/schema_field_description_test.go
  internal/core/encoding.go
  internal/core/key.go
  internal/core/key_test.go
  internal/db/collection.go
  internal/db/collection_index.go
  internal/db/fetcher/errors.go
  internal/db/fetcher/indexer.go
  internal/db/fetcher/indexer_iterators.go
  internal/db/index.go
  internal/db/index_test.go
  internal/db/indexed_docs_test.go
  internal/planner/filter/copy_field.go
  internal/planner/filter/merge.go
  internal/planner/filter/merge_test.go
  internal/planner/filter/split.go
  internal/planner/scan.go
  internal/planner/type_join.go
  internal/utils/slice/slice.go
  internal/utils/slice/slice_test.go
  tests/integration/index/array_composite_test.go
  tests/integration/index/array_test.go
  tests/integration/index/array_unique_composite_test.go
  tests/integration/index/array_unique_test.go
Labels: feature, perf, area/collections

#3105 chore(i): Bump linter (`golangci-lint`) to v1.61
  .github/workflows/lint.yml
  Makefile
  cmd/genopenapi/main.go
  http/client_collection.go
  http/handler_collection.go
  http/handler_store.go
  tests/clients/cli/wrapper_collection.go
  tools/configs/golangci.yaml
Labels: ci/build, code quality

#3098 feat: JSON type coercion
  client/document.go
  client/document_test.go
  client/errors.go
  client/normal_new.go
  client/normal_scalar.go
  client/normal_value.go
  client/normal_value_test.go
  client/normal_void.go
  docs/data_format_changes/i3097-json-type-coercion.md
  go.mod
  go.sum
  internal/connor/connor.go
  internal/connor/eq.go
  internal/core/encoding.go
  internal/planner/mapper/mapper.go
  internal/request/graphql/schema/collection.go
  internal/request/graphql/schema/types/scalars.go
  internal/request/graphql/schema/types/scalars_test.go
  tests/integration/mutation/create/field_kinds/field_kind_json_test.go
  tests/integration/mutation/create/with_variables_test.go
  tests/integration/mutation/update/field_kinds/json_test.go
  tests/integration/query/simple/with_filter/with_eq_json_test.go
  tests/integration/query/simple/with_filter/with_in_json_test.go
  tests/integration/schema/updates/add/field/kind/json_test.go
Labels: area/query

#3124 fix: Prevent mutations from secondary side of relation
  client/document.go
  client/errors.go
  docs/data_format_changes/i3102-no-change-tests-updated.md
  internal/db/collection.go
  internal/db/collection_update.go
  internal/request/graphql/schema/generate.go
  tests/integration/events.go
  tests/integration/mutation/create/field_kinds/one_to_many/with_alias_test.go
  tests/integration/mutation/create/field_kinds/one_to_one/with_alias_test.go
  tests/integration/mutation/create/field_kinds/one_to_one/with_null_value_test.go
  tests/integration/mutation/create/field_kinds/one_to_one/with_simple_test.go
  tests/integration/mutation/update/field_kinds/one_to_many/simple_test.go
  tests/integration/mutation/update/field_kinds/one_to_many/with_alias_test.go
  tests/integration/mutation/update/field_kinds/one_to_one/with_alias_test.go
  tests/integration/mutation/update/field_kinds/one_to_one/with_self_ref_test.go
  tests/integration/mutation/update/field_kinds/one_to_one/with_simple_test.go
  tests/integration/query/one_to_one/with_group_related_id_alias_test.go
  tests/integration/query/one_to_one/with_group_related_id_test.go
  tests/integration/query/one_to_one_multiple/simple_test.go
  tests/integration/query/one_to_one_to_many/simple_test.go
  tests/integration/query/one_to_one_to_one/simple_test.go
  tests/integration/query/one_to_one_to_one/with_order_test.go
  tests/integration/schema/create_one_one_data_test.go
  tests/integration/schema/updates/add/field/kind/doc_id_test.go
  tests/predefined/gen_predefined_test.go
Labels: bug, area/query

#3107 feat: Add replicator retry
  client/db.go
  client/mocks/db.go
  client/replicator.go
  datastore/mocks/txn.go
  datastore/multi.go
  datastore/store.go
  docs/website/references/http/openapi.json
  event/event.go
  http/client.go
  http/client_tx.go
  internal/core/key.go
  internal/db/collection.go
  internal/db/config.go
  internal/db/config_test.go
  internal/db/db.go
  internal/db/errors.go
  internal/db/messages.go
  internal/db/p2p_replicator.go
  net/client.go
  net/client_test.go
  net/peer.go
  net/peer_test.go
  net/server.go
  tests/bench/query/planner/utils.go
  tests/clients/cli/wrapper.go
  tests/clients/cli/wrapper_tx.go
  tests/clients/http/wrapper.go
  tests/clients/http/wrapper_tx.go
  tests/integration/db.go
  tests/integration/net/simple/replicator/with_create_test.go
  tests/integration/net/simple/replicator/with_update_test.go
  tests/integration/test_case.go
  tests/integration/utils.go
Labels: feature, area/p2p

#3122 feat: JSON type filter
  internal/connor/all.go
  internal/connor/any.go
  internal/planner/mapper/mapper.go
  internal/planner/mapper/targetable.go
  internal/request/graphql/schema/generate.go
  internal/request/graphql/schema/manager.go
  internal/request/graphql/schema/types/base.go
  tests/integration/explain/default/with_filter_test.go
  tests/integration/query/json/with_all_test.go
  tests/integration/query/json/with_any_test.go
  tests/integration/query/json/with_eq_test.go
  tests/integration/query/json/with_ge_test.go
  tests/integration/query/json/with_gt_test.go
  tests/integration/query/json/with_in_test.go
  tests/integration/query/json/with_le_test.go
  tests/integration/query/json/with_like_test.go
  tests/integration/query/json/with_lt_test.go
  tests/integration/query/json/with_ne_test.go
  tests/integration/query/json/with_nin_test.go
  tests/integration/query/json/with_nlike_test.go
  tests/integration/query/json/with_none_test.go
  tests/integration/schema/filter_test.go
  tests/integration/schema/simple_test.go
Labels: feature, area/query

#3137 fix(i): Default field value validation
  docs/data_format_changes/i3137-default-value-fix.md
  internal/db/definition_validation.go
  internal/db/errors.go
  internal/request/graphql/schema/collection.go
  internal/request/graphql/schema/errors.go
  tests/integration/collection_description/with_default_fields_test.go
Labels: bug

#3136 test: Add bug bash tests for gql fragments
  tests/integration/query/one_to_one/with_fragments_test.go
Labels: area/testing, code quality, priority/low

#3143 fix(i): Panic in object equal filter
  internal/connor/connor.go
  internal/connor/eq.go
  tests/integration/query/json/with_eq_test.go
Labels: bug, area/query

#3150 fix(i): Aggregate json filter
  internal/planner/mapper/mapper.go
  tests/integration/query/json/with_aggregate_test.go
  tests/integration/query/one_to_many/with_count_filter_test.go
Labels: bug

#3152 fix: Validate GraphQL schemas
  examples/schema/user.graphql
  internal/core/parser.go
  internal/db/schema.go
  internal/db/view.go
  internal/request/graphql/parser.go
  internal/request/graphql/schema/collection.go
  internal/request/graphql/schema/index_parse_test.go
  internal/request/graphql/schema/manager.go
  internal/request/graphql/schema/schema.go
  internal/request/graphql/schema/types/types.go
  tests/bench/query/planner/utils.go
  tests/integration/acp/schema/add_dpi/reject_invalid_arg_type_on_schema_test.go
  tests/integration/collection_description/with_default_fields_test.go
  tests/integration/encryption/commit_test.go
  tests/integration/encryption/peer_share_test.go
  tests/integration/encryption/query_test.go
  tests/integration/encryption/utils.go
  tests/integration/issues/2566_test.go
  tests/integration/issues/2569_test.go
  tests/integration/mutation/create/crdt/pcounter_test.go
  tests/integration/mutation/create/crdt/pncounter_test.go
  tests/integration/mutation/update/crdt/pcounter_test.go
  tests/integration/mutation/update/crdt/pncounter_test.go
  tests/integration/net/simple/peer/crdt/pcounter_test.go
  tests/integration/net/simple/peer/crdt/pncounter_test.go
  tests/integration/net/simple/peer_replicator/crdt/pcounter_test.go
  tests/integration/net/simple/peer_replicator/crdt/pncounter_test.go
  tests/integration/net/simple/replicator/crdt/pcounter_test.go
  tests/integration/net/simple/replicator/crdt/pncounter_test.go
  tests/integration/query/simple/with_cid_doc_id_test.go
  tests/integration/schema/crdt_type_test.go
  tests/integration/utils.go
Labels: bug

#3145 fix(i): Inline array filter types
  internal/connor/all.go
  internal/connor/any.go
  tests/integration/query/inline_array/with_filter_all_test.go
  tests/integration/query/inline_array/with_filter_any_test.go
  tests/integration/query/json/with_all_test.go
  tests/integration/query/json/with_any_test.go
Labels: bug

#3134 refactor(i): Lint casts & move panics under `must` funcs
  cli/p2p_info.go
  cli/purge.go
  cli/utils.go
  http/handler.go
  http/handler_acp.go
  http/handler_ccip.go
  http/handler_collection.go
  http/handler_extras.go
  http/handler_lens.go
  http/handler_p2p.go
  http/handler_store.go
  http/handler_tx.go
  http/middleware.go
  http/utils.go
  tools/configs/golangci.yaml
Labels: code quality

#3170 ci: Freeze goreleaser version and fix amd64 path
  .github/workflows/release.yml
Labels: ci/build

#3175 fix(i): SetReplicator and DeleteReplicator params
  cli/p2p_replicator_delete.go
  cli/p2p_replicator_set.go
  client/mocks/db.go
  client/p2p.go
  client/replicator.go
  docs/website/references/http/openapi.json
  http/client_p2p.go
  http/handler_p2p.go
  http/openapi.go
  internal/db/p2p_replicator.go
  internal/db/p2p_replicator_test.go
  tests/clients/cli/wrapper.go
  tests/clients/http/wrapper.go
  tests/integration/p2p.go
Labels: bug

#3174 fix(i): Panic on aggregate alias
  internal/request/graphql/parser/query.go
  tests/integration/query/commits/simple_test.go
  tests/integration/query/latest_commits/with_doc_id_test.go
  tests/integration/query/simple/with_average_test.go
  tests/integration/query/simple/with_count_test.go
  tests/integration/query/simple/with_max_test.go
  tests/integration/query/simple/with_min_test.go
Labels: bug

#3178 fix: Add Authorization header to CORS allowed headers
  http/middleware.go
  http/server_test.go
Labels: area/api

#3192 refactor: Remove indirection from crdt packages
  internal/core/crdt/base.go
  internal/core/crdt/base_test.go
  internal/core/crdt/composite.go
  internal/core/crdt/counter.go
  internal/core/crdt/lwwreg.go
  internal/core/crdt/lwwreg_test.go
  internal/core/replicated.go
  internal/merkle/crdt/composite.go
  internal/merkle/crdt/counter.go
  internal/merkle/crdt/lwwreg.go
  internal/merkle/crdt/merklecrdt.go
  internal/merkle/crdt/merklecrdt_test.go
Labels: area/crdt, refactor, code quality
