Repository sourcenetwork/defradb, pull requests merged in 2024-09, with the labels that each got.

#2931 chore: Change from ipld traversal to direct link access
  go.sum
  net/sync_dag.go
Labels: area/p2p

#2996 fix(i): Log graphql server address
  http/handler_playground.go
  http/server.go
  node/node.go
Labels: area/logging

#2993 feat: GQL variables and operation name
  cli/request.go
  client/db.go
  client/mocks/db.go
  docs/website/references/cli/defradb_client_query.md
  docs/website/references/http/openapi.json
  go.mod
  go.sum
  http/client.go
  http/handler_store.go
  internal/core/parser.go
  internal/db/request.go
  internal/db/store.go
  internal/db/view.go
  internal/request/graphql/parser.go
  internal/request/graphql/parser/commit.go
  internal/request/graphql/parser/filter.go
  internal/request/graphql/parser/mutation.go
  internal/request/graphql/parser/query.go
  internal/request/graphql/parser/request.go
  internal/request/graphql/parser/subscription.go
  internal/request/graphql/schema/generate.go
  internal/request/graphql/schema/manager.go
  tests/bench/query/planner/utils.go
  tests/clients/cli/wrapper.go
  tests/clients/http/wrapper.go
  tests/integration/mutation/create/with_variables_test.go
  tests/integration/query/one_to_one/with_clashing_id_field_test.go
  tests/integration/query/simple/with_operation_name_test.go
  tests/integration/query/simple/with_variables_test.go
  tests/integration/test_case.go
  tests/integration/utils.go
Labels: area/query

#2994 refactor: Index field directive
  internal/request/graphql/schema/collection.go
  internal/request/graphql/schema/index_parse_test.go
  internal/request/graphql/schema/manager.go
  internal/request/graphql/schema/types/types.go
  tests/integration/index/create_composite_test.go
  tests/integration/index/create_get_test.go
  tests/integration/index/create_unique_composite_test.go
  tests/integration/index/query_with_composite_index_field_order_test.go
  tests/integration/index/query_with_composite_index_only_filter_test.go
  tests/integration/index/query_with_composite_inxed_on_relation_test.go
  tests/integration/index/query_with_relation_filter_test.go
  tests/integration/index/query_with_unique_composite_index_filter_test.go
  tests/integration/index/update_unique_composite_test.go
Labels: bug, area/query

#2997 feat: Default scalar field values
  client/collection_field_description.go
  client/definitions.go
  client/document.go
  docs/website/references/http/openapi.json
  http/client_collection.go
  internal/db/fetcher/encoded_doc.go
  internal/request/graphql/schema/collection.go
  internal/request/graphql/schema/errors.go
  internal/request/graphql/schema/generate.go
  internal/request/graphql/schema/manager.go
  internal/request/graphql/schema/types/types.go
  tests/clients/cli/wrapper_collection.go
  tests/integration/collection_description/updates/replace/fields_test.go
  tests/integration/collection_description/with_default_fields_test.go
  tests/integration/mutation/create/with_default_values_test.go
  tests/integration/view/simple/with_default_value_test.go
Labels: feature, area/query

#3015 ci(i): Fix view-type typo to avoid coverage file name clash
  .github/workflows/test-and-upload-coverage.yml
Labels: ci/build

#3020 fix: Panic with filter on unique composite index on relation
  internal/db/fetcher/indexer_iterators.go
  tests/integration/index/query_with_relation_filter_test.go
  tests/integration/index/query_with_unique_index_on_relation_filter_test.go
Labels: bug, area/query

#3023 fix: Handle missing type in an SDL
  internal/request/graphql/schema/collection.go
  internal/request/graphql/schema/errors.go
  tests/integration/schema/nil_type_test.go
Labels: bug, area/schema

#3021 feat: Add support for one sided relations
  internal/planner/planner.go
  internal/planner/type_join.go
  tests/integration/query/one_to_many/one_sided_test.go
Labels: feature, area/query

#3013 fix: GraphQL null argument parsing
  internal/planner/mapper/targetable.go
  internal/request/graphql/parser/commit.go
  internal/request/graphql/parser/filter.go
  internal/request/graphql/parser/mutation.go
  internal/request/graphql/parser/query.go
  internal/request/graphql/parser/subscription.go
  tests/integration/mutation/create/with_null_input_test.go
  tests/integration/mutation/delete/with_null_input_test.go
  tests/integration/mutation/update/with_null_input_test.go
  tests/integration/query/commits/with_null_input_test.go
  tests/integration/query/simple/with_null_input_test.go
Labels: bug

#3027 ci(i): Use composites & split test matrix into smaller jobs
  .github/composites/install-sourcehub/action.yml
  .github/composites/setup-defradb/action.yml
  .github/composites/test-coverage-with-artifact/action.yml
  .github/workflows/check-data-format-changes.yml
  .github/workflows/test-and-upload-coverage.yml
  .github/workflows/test-coverage.yml
  README.md
Labels: ci/build

#3034 docs(i): Fix incorrect flag and env variable
  README.md
  cli/keyring_export.go
  cli/keyring_generate.go
  cli/keyring_import.go
  docs/website/references/cli/defradb_keyring_export.md
  docs/website/references/cli/defradb_keyring_generate.md
  docs/website/references/cli/defradb_keyring_import.md
Labels: documentation

#3037 fix: Log GQL endpoint correctly on node start
  node/node.go
Labels: bug, documentation, area/api, area/cli

#3035 fix: Queries with filter on 2 rel fields of composite index
  internal/planner/multi.go
  internal/planner/scan.go
  internal/planner/type_join.go
  tests/integration/index/query_with_index_only_filter_test.go
Labels: bug, area/query

#3030 fix(i): Default field value overwrite on update
  internal/request/graphql/schema/generate.go
  tests/integration/mutation/update/with_default_values_test.go
Labels: bug, area/query

#3028 feat: Inline array filters
  internal/connor/all.go
  internal/connor/and.go
  internal/connor/any.go
  internal/connor/connor.go
  internal/connor/eq.go
  internal/connor/none.go
  internal/planner/mapper/mapper.go
  internal/request/graphql/schema/generate.go
  internal/request/graphql/schema/manager.go
  internal/request/graphql/schema/types/base.go
  internal/request/graphql/schema/types/descriptions.go
  tests/integration/query/inline_array/with_filter_all_test.go
  tests/integration/query/inline_array/with_filter_any_test.go
  tests/integration/query/inline_array/with_filter_none_test.go
  tests/integration/query/simple/with_filter/with_and_test.go
  tests/integration/query/simple/with_filter/with_or_test.go
  tests/integration/schema/aggregates/inline_array_test.go
Labels: feature, area/query

#3040 fix: Make GraphQL errors spec compliant
  cli/request.go
  client/db.go
  client/errors.go
  docs/website/references/http/openapi.json
  http/client.go
  http/errors.go
  http/handler_store.go
  http/handler_store_test.go
  http/openapi.go
  http/utils.go
  internal/db/request.go
  internal/db/store.go
  internal/db/subscriptions.go
  internal/request/graphql/parser.go
  tests/clients/cli/wrapper.go
Labels: bug

#3044 refactor: GraphQL order input
  docs/website/references/query-specification/sorting-and-ordering.md
  internal/request/graphql/parser/commit.go
  internal/request/graphql/parser/errors.go
  internal/request/graphql/parser/filter.go
  internal/request/graphql/parser/order.go
  internal/request/graphql/parser/query.go
  internal/request/graphql/schema/generate.go
  internal/request/graphql/schema/types/commits.go
  tests/integration/explain/debug/with_order_test.go
  tests/integration/explain/default/with_order_test.go
  tests/integration/explain/execute/with_order_test.go
  tests/integration/query/one_to_many_to_one/with_order_test.go
  tests/integration/query/simple/with_order_test.go
  tests/integration/query/simple/with_variables_test.go
  tests/integration/schema/aggregates/inline_array_test.go
  tests/integration/schema/aggregates/simple_test.go
  tests/integration/schema/aggregates/top_level_test.go
  tests/integration/schema/default_fields.go
  tests/integration/schema/filter_test.go
  tests/integration/schema/input_type_test.go
Labels: area/query

#3061 refactor: Change from protobuf to cbor for gRPC
  go.mod
  go.sum
  internal/kms/pubsub.go
  net/client.go
  net/codec.go
  net/dialer.go
  net/grpc.go
  net/pb/Makefile
  net/pb/net.pb.go
  net/pb/net.proto
  net/pb/net_grpc.pb.go
  net/pb/net_vtproto.pb.go
  net/peer.go
  net/server.go
  net/server_test.go
Labels: refactor, area/p2p

#3066 feat: GraphQL fragments
  go.mod
  go.sum
  internal/request/graphql/parser/mutation.go
  internal/request/graphql/parser/query.go
  internal/request/graphql/parser/request.go
  internal/request/graphql/parser/subscription.go
  tests/integration/query/simple/with_fragments_test.go
Labels: feature, area/query

#3068 fix(i): Sort out invalid testing framework node indexing
  tests/integration/acp/p2p/create_test.go
  tests/integration/acp/p2p/delete_test.go
  tests/integration/acp/p2p/update_test.go
  tests/integration/test_case.go
  tests/integration/utils.go
Labels: bug, area/testing

#3077 fix(i): Validate nearby relation fields in SchemaPatch
  internal/db/definition_validation.go
  internal/db/schema.go
  tests/integration/schema/updates/add/field/with_relation_test.go
Labels: bug, area/schema

#3075 feat: GraphQL upsert mutation
  client/request/consts.go
  client/request/mutation.go
  internal/planner/create.go
  internal/planner/errors.go
  internal/planner/explain.go
  internal/planner/mapper/mapper.go
  internal/planner/mapper/mutation.go
  internal/planner/operations.go
  internal/planner/planner.go
  internal/planner/update.go
  internal/planner/upsert.go
  internal/request/graphql/parser/mutation.go
  internal/request/graphql/schema/descriptions.go
  internal/request/graphql/schema/generate.go
  tests/integration/explain.go
  tests/integration/explain/debug/upsert_test.go
  tests/integration/explain/default/upsert_test.go
  tests/integration/explain/execute/upsert_test.go
  tests/integration/mutation/upsert/simple_test.go
Labels: feature, area/query

#3080 fix(i): Null compound filter panic
  internal/connor/and.go
  internal/connor/or.go
  internal/planner/mapper/mapper.go
  internal/planner/mapper/targetable.go
  internal/request/graphql/schema/generate.go
  tests/integration/query/simple/with_null_input_test.go
  tests/integration/schema/default_fields.go
  tests/integration/schema/filter_test.go
Labels: bug

#3091 ci(i): Fix vulnerabilities scan by ignoring x/crises
  .github/workflows/check-vulnerabilities.yml
  Makefile
Labels: ci/build
