Repository sourcenetwork/defradb, pull requests merged in 2024-11, with the labels that each got.

#3200 refactor: Simplify merkle/crdt code
  internal/db/base/collection_keys.go
  internal/db/collection.go
  internal/db/collection_delete.go
  internal/db/fetcher/versioned.go
  internal/db/merge.go
  internal/keys/datastore_doc.go
  internal/merkle/crdt/composite.go
  internal/merkle/crdt/counter.go
  internal/merkle/crdt/errors.go
  internal/merkle/crdt/lwwreg.go
  internal/merkle/crdt/merklecrdt.go
Labels: area/crdt, refactor, code quality

#3201 feat: Filter alias target
  client/request/filter.go
  internal/connor/connor.go
  internal/connor/eq.go
  internal/connor/key.go
  internal/connor/not_test.go
  internal/core/doc.go
  internal/planner/filter/copy_field.go
  internal/planner/filter/copy_field_test.go
  internal/planner/mapper/errors.go
  internal/planner/mapper/mapper.go
  internal/planner/mapper/targetable.go
  internal/request/graphql/parser/filter.go
  internal/request/graphql/schema/generate.go
  tests/integration/query/one_to_many/with_count_test.go
  tests/integration/query/one_to_many/with_filter_test.go
  tests/integration/query/simple/with_filter/with_alias_test.go
  tests/integration/schema/aggregates/inline_array_test.go
  tests/integration/schema/default_fields.go
  tests/integration/schema/filter_test.go
Labels: feature

#3210 refactor: Rework core.Spans
  internal/core/data.go
  internal/core/data_test.go
  internal/db/collection_get.go
  internal/db/collection_index.go
  internal/db/fetcher/dag.go
  internal/db/fetcher/errors.go
  internal/db/fetcher/fetcher.go
  internal/db/fetcher/indexer.go
  internal/db/fetcher/mocks/fetcher.go
  internal/db/fetcher/versioned.go
  internal/db/fetcher_test.go
  internal/keys/datastore_doc.go
  internal/keys/headstore_doc.go
  internal/keys/key.go
  internal/lens/fetcher.go
  internal/planner/arbitrary_join.go
  internal/planner/average.go
  internal/planner/commit.go
  internal/planner/count.go
  internal/planner/create.go
  internal/planner/delete.go
  internal/planner/group.go
  internal/planner/lens.go
  internal/planner/limit.go
  internal/planner/max.go
  internal/planner/min.go
  internal/planner/multi.go
  internal/planner/operation.go
  internal/planner/order.go
  internal/planner/pipe.go
  internal/planner/planner.go
  internal/planner/scan.go
  internal/planner/select.go
  internal/planner/sum.go
  internal/planner/top.go
  internal/planner/type_join.go
  internal/planner/update.go
  internal/planner/upsert.go
  internal/planner/values.go
  internal/planner/view.go
  tests/integration/explain/default/delete_test.go
Labels: area/query, refactor, code quality

#3216 feat: Add support for branchable collections
  client/collection_description.go
  docs/data_format_changes/i3038-branchable-collections.md
  docs/website/references/http/openapi.json
  internal/core/block/block.go
  internal/core/crdt/collection.go
  internal/core/crdt/composite.go
  internal/core/crdt/ipld_union.go
  internal/db/collection.go
  internal/db/collection_delete.go
  internal/db/definition_validation.go
  internal/db/errors.go
  internal/db/fetcher/dag.go
  internal/db/fetcher/versioned.go
  internal/db/iterator.go
  internal/db/merge.go
  internal/keys/datastore_doc.go
  internal/keys/headstore.go
  internal/keys/headstore_collection.go
  internal/keys/headstore_doc.go
  internal/merkle/clock/clock.go
  internal/merkle/clock/clock_test.go
  internal/merkle/clock/heads.go
  internal/merkle/clock/heads_test.go
  internal/merkle/crdt/collection.go
  internal/merkle/crdt/composite.go
  internal/planner/commit.go
  internal/planner/select.go
  internal/request/graphql/parser/commit.go
  internal/request/graphql/schema/collection.go
  internal/request/graphql/schema/schema.go
  internal/request/graphql/schema/types/descriptions.go
  internal/request/graphql/schema/types/types.go
  net/server_test.go
  tests/integration/collection_description/branchable_test.go
  tests/integration/collection_description/updates/replace/branchable_test.go
  tests/integration/events.go
  tests/integration/explain/default/dagscan_test.go
  tests/integration/query/commits/branchables/cid_doc_id_test.go
  tests/integration/query/commits/branchables/cid_test.go
  tests/integration/query/commits/branchables/create_test.go
  tests/integration/query/commits/branchables/delete_test.go
  tests/integration/query/commits/branchables/field_id_test.go
  tests/integration/query/commits/branchables/if_test.go
  tests/integration/query/commits/branchables/peer_test.go
  tests/integration/query/commits/branchables/simple_test.go
  tests/integration/query/commits/branchables/update_test.go
  tests/integration/query/commits/with_null_input_test.go
  tests/integration/query/simple/with_cid_test.go
  tests/integration/results.go
Labels: feature, area/crdt, area/collections

#3234 test(i): Skip test when detecting changes
  tests/integration/query/simple/with_cid_test.go
Labels: area/testing, ci/build, code quality

#3217 feat: Order alias target
  client/request/consts.go
  client/request/filter.go
  internal/planner/mapper/mapper.go
  internal/planner/mapper/targetable.go
  internal/request/graphql/parser/errors.go
  internal/request/graphql/parser/filter.go
  internal/request/graphql/parser/order.go
  internal/request/graphql/schema/generate.go
  tests/integration/query/one_to_one/with_order_test.go
  tests/integration/query/simple/with_order_test.go
Labels: feature

#3237 feat: Support for descending fields CLI index creation
  cli/errors.go
  cli/index_create.go
  docs/website/references/cli/defradb_client_index_create.md
  tests/clients/cli/wrapper_collection.go
  tests/integration/index/create_unique_composite_test.go
Labels: area/cli

#3232 refactor: Consolidate node-related fields into a struct
  tests/integration/acp.go
  tests/integration/db.go
  tests/integration/events.go
  tests/integration/lens.go
  tests/integration/p2p.go
  tests/integration/state.go
  tests/integration/utils.go
Labels: area/testing, refactor

#3241 fix(i): Remove flakyness of AES decrypt test
  crypto/aes_test.go
Labels: bug, area/testing

#3247 feat(i): Handle collection commits over P2P
  internal/db/merge.go
  internal/db/merge_test.go
  internal/db/messages.go
  net/peer.go
  net/server.go
  tests/integration/acp.go
  tests/integration/events.go
  tests/integration/query/commits/branchables/peer_index_test.go
  tests/integration/query/commits/branchables/peer_test.go
  tests/integration/query/commits/branchables/peer_update_test.go
  tests/integration/state.go
  tests/integration/utils.go
Labels: feature, area/p2p

#3256 feat: Add support for cid-only time travel queries
  internal/db/fetcher/versioned.go
  internal/planner/select.go
  internal/request/graphql/schema/descriptions.go
  tests/integration/query/simple/with_cid_test.go
Labels: feature, area/query

#3260 feat: Add support for branchable collection time-traveling
  internal/db/fetcher/versioned.go
  internal/planner/select.go
  internal/request/graphql/schema/descriptions.go
  tests/integration/query/simple/with_cid_branchable_test.go
  tests/integration/query/simple/with_cid_doc_id_branchable_test.go
  tests/integration/query/simple/with_cid_doc_id_test.go
Labels: bug, feature, area/query

#3263 fix: Resolve CORS errors in OpenAPI tab of Playground
  docs/website/references/http/openapi.json
  http/openapi.go
Labels: bug

#3267 ci: Fix the gql mutation running in all tests
  tests/integration/utils.go
Labels: ci/build

#3254 feat: Add ability to add/delete relationship for all actors
  acp/README.md
  acp/acp_local.go
  acp/acp_source_hub.go
  cli/acp_relationship_add.go
  client/db.go
  docs/website/references/cli/defradb_client_acp_relationship_add.md
  tests/integration/acp.go
  tests/integration/acp/relationship/doc_actor/add/with_target_all_actors_gql_test.go
  tests/integration/acp/relationship/doc_actor/add/with_target_all_actors_test.go
  tests/integration/acp/relationship/doc_actor/delete/with_target_all_actors_test.go
  tests/integration/identity.go
  tests/integration/state.go
  tests/integration/test_case.go
Labels: feature, area/acp
