Repository sourcenetwork/defradb, pull requests merged in 2024-03, with the labels that each got.

#2335 feat: Reverted order for indexed fields
  client/document.go
  client/field.go
  client/index.go
  client/index_test.go
  core/encoding.go
  core/errors.go
  core/key.go
  core/key_test.go
  db/collection.go
  db/collection_delete.go
  db/collection_index.go
  db/errors.go
  db/fetcher/encoded_doc.go
  db/fetcher/errors.go
  db/fetcher/indexer.go
  db/fetcher/indexer_iterators.go
  db/index.go
  db/index_test.go
  db/indexed_docs_test.go
  docs/data_format_changes/i2229-order-direction-for-indexed-fields.md
  encoding/bytes.go
  encoding/bytes_test.go
  encoding/encoding.go
  encoding/errors.go
  encoding/field_value.go
  encoding/field_value_test.go
  encoding/float.go
  encoding/float_test.go
  encoding/int.go
  encoding/int_test.go
  encoding/null.go
  encoding/null_test.go
  encoding/string.go
  encoding/string_test.go
  encoding/type.go
  encoding/type_test.go
  go.mod
  lens/fetcher.go
  request/graphql/schema/collection.go
  request/graphql/schema/generate.go
  request/graphql/schema/index_parse_test.go
  request/graphql/schema/types/types.go
  tests/integration/index/create_composite_test.go
  tests/integration/index/create_get_test.go
  tests/integration/index/create_unique_composite_test.go
  tests/integration/index/create_unique_test.go
  tests/integration/index/query_with_composite_index_field_order_test.go
  tests/integration/index/query_with_composite_index_only_filter_test.go
  tests/integration/index/query_with_index_only_field_order_test.go
  tests/integration/index/query_with_index_only_filter_test.go
  tests/integration/index/query_with_unique_composite_index_filter_test.go
  tests/integration/index/query_with_unique_index_only_filter_test.go
  tests/integration/test_case.go
  tests/integration/utils2.go
  tools/configs/golangci.yaml
Labels: feature, area/query, area/datastore, perf

#2374 fix(i): Server dump fails
  cli/server_dump.go
Labels: bug

#2377 fix(i): JSON scalar introspection
  request/graphql/schema/manager.go
Labels: bug

#2375 fix: Add validation to JSON fields
  client/document.go
  client/document_test.go
  client/errors.go
  tests/integration/mutation/create/field_kinds/field_kind_json_test.go
Labels: bug

#2369 fix: Add missing directive definitions
  request/graphql/schema/collection.go
  request/graphql/schema/manager.go
  request/graphql/schema/types/descriptions.go
  request/graphql/schema/types/types.go
Labels: bug, area/schema

#2368 feat: Add case insensitive `like` operator
  connor/connor.go
  connor/ilike.go
  connor/ilike_test.go
  connor/like.go
  connor/nilike.go
  connor/nilike_test.go
  connor/nlike_test.go
  db/fetcher/indexer_iterators.go
  request/graphql/schema/types/base.go
  request/graphql/schema/types/descriptions.go
  tests/integration/index/query_with_composite_index_field_order_test.go
  tests/integration/index/query_with_index_combined_filter_test.go
  tests/integration/index/query_with_unique_composite_index_filter_test.go
  tests/integration/index/query_with_unique_index_only_filter_test.go
  tests/integration/query/one_to_many/with_filter_test.go
  tests/integration/query/simple/with_filter/with_like_string_test.go
  tests/integration/query/simple/with_filter/with_nlike_string_test.go
  tests/integration/schema/aggregates/inline_array_test.go
Labels: feature

#2378 fix: Update GetCollections behaviour
  cli/collection_describe.go
  client/db.go
  db/collection.go
  tests/integration/schema/updates/with_schema_branch_test.go
Labels: area/collections, area/cli

#2383 tools(i): Enable nilness linter
  http/handler_lens.go
  request/graphql/parser/request.go
  tools/configs/golangci.yaml
Labels: config-change

#2385 fix: Make returned collections respect explicit transactions
  client/db.go
  db/txn_db.go
Labels: bug, area/collections

#2387 test(i): Convert old update tests to newer framework
  docs/data_format_changes/i2386-no-change-tests-updated.md
  tests/integration/query/one_to_many/with_cid_doc_id_test.go
  tests/integration/query/simple/with_cid_doc_id_test.go
  tests/integration/utils.go
Labels: area/testing, code quality

#2390 fix: Make peers sync secondary index
  client/collection.go
  client/index.go
  db/collection_index.go
  db/index.go
  db/index_test.go
  db/txn_db.go
  http/client.go
  http/client_collection.go
  http/errors.go
  net/server.go
  tests/clients/cli/errors.go
  tests/clients/cli/wrapper.go
  tests/clients/cli/wrapper_cli.go
  tests/clients/cli/wrapper_collection.go
  tests/integration/index/index_p2p_test.go
Labels: bug, area/datastore, area/p2p

#2391 fix: Add missing logs at startup
  http/server.go
  http/server_test.go
  net/peer.go
  node/node.go
Labels: bug, area/cli

#2395 fix(i): Move cache action after goreleaser action
  .github/workflows/release.yml
Labels: bug, ci/build

#2402 feat: Add PatchCollection
  cli/cli.go
  cli/collection_patch.go
  cli/schema_patch.go
  client/db.go
  client/mocks/db.go
  db/collection.go
  db/description/collection.go
  db/errors.go
  db/txn_db.go
  http/client.go
  http/handler_store.go
  tests/clients/cli/wrapper.go
  tests/clients/http/wrapper.go
  tests/integration/collection_description/simple_test.go
  tests/integration/collection_description/updates/add/collections_test.go
  tests/integration/collection_description/updates/add/sources_test.go
  tests/integration/collection_description/updates/copy/name_test.go
  tests/integration/collection_description/updates/move/name_test.go
  tests/integration/collection_description/updates/remove/collections_test.go
  tests/integration/collection_description/updates/remove/name_test.go
  tests/integration/collection_description/updates/replace/fields_test.go
  tests/integration/collection_description/updates/replace/id_test.go
  tests/integration/collection_description/updates/replace/indexes_test.go
  tests/integration/collection_description/updates/replace/name_test.go
  tests/integration/collection_description/updates/replace/root_id_test.go
  tests/integration/collection_description/updates/replace/schema_version_id_test.go
  tests/integration/collection_description/updates/replace/sources_test.go
  tests/integration/collection_description/updates/test/name_test.go
  tests/integration/schema/updates/add/field/kind/foreign_object_array_test.go
  tests/integration/schema/updates/add/field/kind/foreign_object_test.go
  tests/integration/schema/updates/add/field/with_index_test.go
  tests/integration/schema/updates/add/simple_test.go
  tests/integration/schema/updates/copy/simple_test.go
  tests/integration/schema/updates/replace/simple_test.go
  tests/integration/test_case.go
  tests/integration/utils2.go
Labels: feature, area/collections

#2421 feat: Add Defra-Lens support for branching schema
  lens/fetcher.go
  lens/history.go
  lens/lens.go
  tests/integration/schema/migrations/query/with_p2p_schema_branch_test.go
  tests/integration/schema/migrations/query/with_schema_branch_test.go
  tests/integration/utils2.go
Labels: feature, area/schema

#2445 refactor: Rewrite convertImmutable
  client/value.go
Labels: code quality

#2443 refactor: Clean up client/request package
  client/request/aggregate.go
  client/request/cid.go
  client/request/commit.go
  client/request/doc_ids.go
  client/request/field.go
  client/request/filter.go
  client/request/group.go
  client/request/limit.go
  client/request/mutation.go
  client/request/offset.go
  client/request/order.go
  client/request/select.go
  client/request/subscription.go
  db/collection_update.go
  planner/mapper/mapper.go
  planner/planner.go
  planner/view.go
  request/graphql/parser/commit.go
  request/graphql/parser/mutation.go
  request/graphql/parser/query.go
  request/graphql/parser/request.go
  request/graphql/parser/subscription.go
Labels: documentation, area/api, code quality

#2450 ci(i): Disable windows build
  .github/workflows/test-and-upload-coverage.yml
Labels: ci/build

#2404 refactor: Add NormalValue
  client/document.go
  client/errors.go
  client/normal_array.go
  client/normal_array_of_nillables.go
  client/normal_new.go
  client/normal_nil.go
  client/normal_nillable_array.go
  client/normal_nillable_array_of_nillables.go
  client/normal_nillable_scalar.go
  client/normal_scalar.go
  client/normal_util.go
  client/normal_value.go
  client/normal_value_test.go
  client/normal_void.go
  client/schema_field_description.go
  client/value.go
  core/encoding.go
  core/errors.go
  core/key.go
  core/key_test.go
  db/fetcher/indexer.go
  db/fetcher/indexer_iterators.go
  db/index.go
  db/indexed_docs_test.go
  encoding/field_value.go
  encoding/field_value_test.go
  tests/integration/index/query_with_index_only_field_order_test.go
  tests/integration/index/query_with_index_only_filter_test.go
  tests/integration/index/query_with_unique_index_only_filter_test.go
  tests/integration/query/simple/with_filter/with_in_test.go
Labels: refactor

#2462 feat: Force explicit primary decl. in SDL for one-ones
  client/errors.go
  db/collection.go
  db/errors.go
  request/graphql/schema/descriptions_test.go
  request/graphql/schema/relations.go
  tests/gen/gen_auto_test.go
  tests/integration/backup/one_to_one/export_test.go
  tests/integration/backup/one_to_one/import_test.go
  tests/integration/explain/fixture.go
  tests/integration/index/query_with_relation_filter_test.go
  tests/integration/mutation/create/field_kinds/one_to_one_to_one/utils.go
  tests/integration/mutation/delete/field_kinds/one_to_one_to_one/utils.go
  tests/integration/schema/one_one_test.go
  tests/integration/schema/relations_test.go
  tests/integration/view/one_to_one/with_transform_test.go
  tests/predefined/gen_predefined_test.go
Labels: feature, area/schema
