Repository sourcenetwork/defradb, pull requests merged in 2024-01, with the labels that each got.

#2178 fix: Handle multiple nil values on unique indexed fields
  db/collection_index.go
  db/errors.go
  db/index.go
  tests/integration/index/create_unique_test.go
  tests/integration/index/query_with_unique_index_only_filter_test.go
Labels: bug

#2188 test(i): Skip tests in change detector without split
  tests/integration/utils2.go
Labels: area/testing

#2185 fix(i): Retain embedded schema within gql types on reload
  db/collection.go
  db/description/schema.go
  db/schema.go
  db/view.go
  tests/integration/schema/simple_test.go
  tests/integration/view/one_to_one/identical_schema_test.go
  tests/integration/view/one_to_one/simple_test_test.go
  tests/integration/view/one_to_one/with_restart_test.go
Labels: bug, area/schema

#2167 feat: Mutation typed input
  client/document.go
  client/request/consts.go
  client/request/mutation.go
  planner/create.go
  planner/explain.go
  planner/mapper/mapper.go
  planner/mapper/mutation.go
  planner/update.go
  request/graphql/parser/mutation.go
  request/graphql/schema/descriptions.go
  request/graphql/schema/errors.go
  request/graphql/schema/generate.go
  tests/integration/events/simple/with_create_txn_test.go
  tests/integration/explain/debug/create_test.go
  tests/integration/explain/debug/update_test.go
  tests/integration/explain/default/create_test.go
  tests/integration/explain/default/update_test.go
  tests/integration/explain/execute/create_test.go
  tests/integration/explain/execute/update_test.go
  tests/integration/gql.go
  tests/integration/mutation/create/field_kinds/one_to_many/utils.go
  tests/integration/mutation/create/field_kinds/one_to_many/with_alias_test.go
  tests/integration/mutation/create/field_kinds/one_to_many/with_simple_test.go
  tests/integration/mutation/create/field_kinds/one_to_one/utils.go
  tests/integration/mutation/create/field_kinds/one_to_one/with_alias_test.go
  tests/integration/mutation/create/field_kinds/one_to_one/with_simple_test.go
  tests/integration/mutation/create/field_kinds/one_to_one_to_one/with_txn_test.go
  tests/integration/mutation/create/simple_test.go
  tests/integration/mutation/create/with_version_test.go
  tests/integration/mutation/mix/with_txn_test.go
  tests/integration/mutation/special/invalid_operation_test.go
  tests/integration/mutation/update/crdt/pncounter_test.go
  tests/integration/mutation/update/field_kinds/date_time_test.go
  tests/integration/mutation/update/field_kinds/one_to_many/simple_test.go
  tests/integration/mutation/update/field_kinds/one_to_many/with_alias_test.go
  tests/integration/mutation/update/field_kinds/one_to_one/with_alias_test.go
  tests/integration/mutation/update/field_kinds/one_to_one/with_simple_test.go
  tests/integration/mutation/update/with_filter_test.go
  tests/integration/mutation/update/with_id_test.go
  tests/integration/mutation/update/with_ids_test.go
  tests/integration/query/one_to_many/with_id_field_test.go
  tests/integration/schema/migrations/query/with_update_test.go
  tests/integration/schema/updates/add/field/kind/foreign_object_array_test.go
  tests/integration/schema/updates/add/field/kind/foreign_object_test.go
  tests/integration/subscription/subscription_test.go
  tests/integration/utils2.go
Labels: feature, area/query, area/parser

#2192 fix(i): Handle field in view query but not view SDL
  core/doc.go
  planner/view.go
  tests/integration/view/one_to_many/simple_test.go
  tests/integration/view/one_to_many/with_count_test.go
  tests/integration/view/one_to_one/simple_test.go
  tests/integration/view/simple/simple_test.go
Labels: bug, area/query

#2193 fix(i): Dont build mutation input types for embedded schema
  request/graphql/schema/generate.go
  tests/integration/view/one_to_many/simple_test.go
Labels: bug, area/query

#2186 fix: Add entropy to counter CRDT type updates
  core/crdt/pncounter.go
  docs/data_format_changes/i2186-adding-entropy-to-pn-counter.md
  merkle/crdt/pncounter.go
  tests/integration/mutation/create/crdt/pncounter_test.go
  tests/integration/net/state/simple/peer/crdt/pncounter_test.go
  tests/integration/query/simple/with_cid_doc_id_test.go
Labels: area/crdt

#2202 fix(i): Remove default collection fields from gql view types
  request/graphql/schema/generate.go
  tests/integration/schema/default_fields.go
  tests/integration/view/one_to_many/with_introspection_test.go
  tests/integration/view/simple/with_introspection_test.go
Labels: bug, area/query

#2222 fix(i): Prevent double-sided relations in views
  request/graphql/schema/collection.go
  request/graphql/schema/errors.go
  tests/integration/view/one_to_many/simple_test.go
Labels: bug, area/query

#2220 test(i): Add view of view tests
  tests/integration/view/one_to_many/simple_test.go
  tests/integration/view/simple/simple_test.go
Labels: area/query, area/testing, code quality

#2225 fix(i): Remove deprecated tcpaddr flag from readme
  README.md
Labels: documentation

#2231 chore(i): Split build by OS for release workflow
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: ci/build

#2223 refactor: Make CollectionDescription.Name Option
  cli/collection.go
  client/collection.go
  client/descriptions.go
  client/errors.go
  core/key.go
  core/key_test.go
  db/backup.go
  db/collection.go
  db/collection_index.go
  db/collection_update.go
  db/description/collection.go
  db/index_test.go
  db/indexed_docs_test.go
  db/view.go
  docs/data_format_changes/i2198-sec-index-key-change.md
  http/client_collection.go
  net/peer_replicator.go
  planner/datasource.go
  planner/scan.go
  planner/select.go
  planner/type_join.go
  planner/view.go
  request/graphql/schema/collection.go
  request/graphql/schema/descriptions_test.go
  request/graphql/schema/generate.go
  tests/clients/cli/wrapper_collection.go
  tests/gen/cli/gendocs.go
  tests/gen/gen_auto.go
  tests/gen/gen_auto_config.go
  tests/gen/gen_auto_test.go
  tests/gen/schema_parser.go
  tests/integration/utils2.go
  tests/predefined/gen_predefined.go
Labels: area/query, area/collections, refactor

#2195 chore: Bump to GoLang v1.21
  .github/workflows/build-dependencies.yml
  .github/workflows/check-vulnerabilities.yml
  .github/workflows/lint-then-benchmark.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/start-binary.yml
  .github/workflows/test-and-upload-coverage.yml
  Makefile
  go.mod
  go.sum
  tools/cloud/aws/packer/build_aws_ami.pkr.hcl
  tools/configs/golangci.yaml
  tools/defradb.containerfile
Labels: bump

#2226 feat: Add composite indexes
  client/index.go
  client/index_test.go
  db/collection_index.go
  db/errors.go
  db/fetcher/errors.go
  db/fetcher/indexer.go
  db/fetcher/indexer_iterators.go
  db/index.go
  db/index_test.go
  db/indexed_docs_test.go
  planner/filter/copy_field.go
  planner/filter/copy_field_test.go
  planner/filter/normalize.go
  planner/filter/split.go
  planner/filter/split_test.go
  planner/planner.go
  planner/scan.go
  planner/select.go
  planner/type_join.go
  tests/integration/explain_result_asserter.go
  tests/integration/index/create_composite_test.go
  tests/integration/index/create_unique_composite_test.go
  tests/integration/index/create_unique_test.go
  tests/integration/index/query_with_composite_index_only_filter_test.go
  tests/integration/index/query_with_index_combined_filter_test.go
  tests/integration/index/query_with_index_only_filter_test.go
  tests/integration/index/query_with_relation_filter_test.go
  tests/integration/index/query_with_unique_composite_index_filter_test.go
  tests/integration/index/query_with_unique_index_only_filter_test.go
  tests/integration/test_case.go
  tests/integration/utils2.go
Labels: feature, area/query, perf

#2242 ci(i): Fix and document release workflow logic
  .github/workflows/release.yml
Labels: ci/build

#2235 feat: Generate OpenAPI command
  cmd/genopenapi/main.go
  http/handler.go
Labels: area/api

#2241 ci(i): Add YAML linter
  .github/dependabot.yml
  .github/workflows/build-then-deploy-ami.yml
  .github/workflows/combine-bot-prs.yml
  .github/workflows/lint-then-benchmark.yml
  .github/workflows/lint.yml
  .github/workflows/preview-ami-with-terraform-plan.yml
  .github/workflows/test-and-upload-coverage.yml
  .github/workflows/validate-containerfile.yml
  .goreleaser.yaml
  Makefile
  tools/cloud/akash/deploy.yaml
  tools/configs/yamllint.yaml
Labels: ci/build, code quality

#2246 refactor(i): Delete dead code in `db.addSchema` func
  db/schema.go
Labels: code quality

#2254 feat: Add JSON scalar
  client/descriptions.go
  client/document.go
  request/graphql/schema/collection.go
  request/graphql/schema/descriptions.go
  request/graphql/schema/types/scalars.go
  request/graphql/schema/types/scalars_test.go
  tests/integration/schema/updates/add/field/kind/invalid_test.go
  tests/integration/schema/updates/add/field/kind/json_test.go
Labels: area/schema

#2256 test(i): Document doc sync before schema update bug
  tests/integration/net/state/simple/peer/with_create_add_field_test.go
Labels: bug, area/query, area/schema

#2266 fix: Load root dir before loading config
  cli/utils.go
  config/config.go
Labels: bug, area/config

#2269 fix(i): Revert removal of root dir check in LoadWithRootDIr
  config/config.go
Labels: bug, area/config

#2258 refactor: Decouple net config
  README.md
  cli/start.go
  config/config.go
  config/config_test.go
  config/configfile_yaml.gotmpl
  net/config.go
  net/config_test.go
  net/dialer_test.go
  net/node.go
  net/node_test.go
  net/peer_test.go
  tests/gen/cli/util_test.go
  tests/integration/net/order/utils.go
  tests/integration/p2p.go
  tests/integration/utils2.go
Labels: area/config

#2275 refactor: Remove unused Delete field from client.Document
  client/document.go
  client/value.go
Labels: refactor, code quality
