Repository sourcenetwork/defradb, pull requests merged in 2024-06, with the labels that each got.

#2669 ci(i): Update codecov to v4
  .github/workflows/test-and-upload-coverage.yml
Labels: ci/build

#2672 test(i): Add txn conflict documentation
  datastore/txn_test.go
Labels: area/datastore

#2682 test: Add relation substitute mechanic to tests
  tests/integration/index/query_with_compound_filter_relation_test.go
  tests/integration/mutation/create/field_kinds/one_to_many/with_alias_test.go
  tests/integration/mutation/create/field_kinds/one_to_many/with_simple_test.go
  tests/integration/test_case.go
  tests/integration/utils2.go
Labels: area/testing, code quality

#2670 feat: Sec. indexes on relations
  client/normal_nil.go
  client/normal_value_test.go
  client/schema_field_description.go
  docs/data_format_changes/i2670-sec-index-on-relations.md
  internal/db/collection_index.go
  internal/db/index.go
  internal/planner/explain.go
  internal/planner/mapper/mapper.go
  internal/planner/mapper/select.go
  internal/planner/planner.go
  internal/planner/select.go
  internal/planner/type_join.go
  tests/integration/explain/execute/with_count_test.go
  tests/integration/index/query_with_relation_filter_test.go
Labels: area/query, perf

#2679 ci(i): Add workflow to detect out of date mocks
  .github/workflows/check-mocks.yml
  Makefile
  tests/README.md
Labels: ci/build

#2686 refactor: Replace subscription events publisher
  cli/request.go
  client/db.go
  http/client.go
  http/handler_ccip.go
  http/handler_store.go
  internal/db/request.go
  internal/db/subscriptions.go
  tests/clients/cli/wrapper.go
  tests/integration/utils2.go
Labels: refactor

#2693 ci(i): Add check to keep table of contents up-to-date
  .github/workflows/check-cli-documentation.yml
  .github/workflows/check-documentation.yml
  .github/workflows/check-http-documentation.yml
  Makefile
  README.md
  tools/scripts/md-toc/README.md
  tools/scripts/md-toc/gh-md-toc
Labels: documentation, ci/build

#2697 ci(i): Add action to ensure tidyness
  .github/workflows/check-tidy.yml
Labels: ci/build

#2698 refactor: Change counters to support encryption
  docs/data_format_changes/i2696-support-encryption-for-counters.md
  internal/core/block/block.go
  internal/core/crdt/counter.go
  internal/core/crdt/errors.go
  internal/core/crdt/ipld_union.go
  internal/merkle/crdt/counter.go
  internal/merkle/crdt/merklecrdt.go
  tests/integration/query/simple/with_cid_doc_id_test.go
Labels: area/crdt, refactor

#2706 refactor: Extract definition stuff from collection.go
  internal/db/collection.go
  internal/db/collection_define.go
  internal/db/definition_validation.go
  internal/db/schema.go
Labels: area/schema, area/collections, refactor, code quality

#2708 feat: Add async transaction callbacks
  datastore/concurrent_txn.go
  datastore/mocks/txn.go
  datastore/txn.go
  datastore/txn_test.go
  http/client_tx.go
  tests/bench/query/planner/utils.go
  tests/clients/cli/wrapper_tx.go
  tests/clients/http/wrapper_tx.go
Labels: feature, area/datastore

#2713 fix: Race condition when testing CLI
  cli/config.go
  cli/config_test.go
  cli/root.go
  cli/start.go
  cli/utils.go
Labels: bug

#2715 chore(i): Update pubsub rpc version
  go.mod
  go.sum
Labels: dependencies

#2720 refactor: Rework definition validation
  internal/db/collection_define.go
  internal/db/definition_validation.go
  internal/db/errors.go
  internal/db/schema.go
  internal/db/view.go
  tests/integration/collection_description/updates/copy/name_test.go
  tests/integration/collection_description/updates/replace/name_test.go
  tests/integration/schema/get_schema_test.go
  tests/integration/schema/migrations/query/simple_test.go
  tests/integration/schema/migrations/query/with_doc_id_test.go
  tests/integration/schema/migrations/query/with_inverse_test.go
  tests/integration/schema/migrations/query/with_p2p_schema_branch_test.go
  tests/integration/schema/migrations/query/with_p2p_test.go
  tests/integration/schema/migrations/query/with_restart_test.go
  tests/integration/schema/migrations/query/with_set_default_test.go
  tests/integration/schema/migrations/query/with_txn_test.go
  tests/integration/schema/migrations/query/with_update_test.go
  tests/integration/schema/migrations/simple_test.go
  tests/integration/schema/one_one_test.go
  tests/integration/schema/updates/add/field/create_update_test.go
  tests/integration/schema/updates/add/field/simple_test.go
  tests/integration/schema/updates/add/simple_test.go
  tests/integration/schema/updates/copy/field/simple_test.go
  tests/integration/schema/updates/copy/simple_test.go
  tests/integration/schema/updates/remove/simple_test.go
  tests/integration/schema/updates/replace/simple_test.go
  tests/integration/schema/updates/with_schema_branch_test.go
  tests/integration/schema/with_update_set_default_test.go
Labels: area/schema, area/collections, refactor, code quality

#2723 fix: Resolve incorrect merge conflict
  datastore/badger/v4/datastore_test.go
  datastore/memory/txn.go
  datastore/memory/txn_test.go
  datastore/txn_test.go
Labels: bug, area/datastore

#2719 fix: Merge retry logic
  events/dag_sync.go
  go.mod
  go.sum
  internal/db/merge.go
  internal/db/merge_test.go
  net/process.go
  net/server.go
  net/server_test.go
  net/sync_dag.go
Labels: bug, area/db-system

#2732 ci: Cache dependencies to speed up test runs
  .github/workflows/test-and-upload-coverage.yml
Labels: ci/build

#2738 fix(i): Convert error logs to `ErrorE` func
  go.mod
  go.sum
  internal/db/merge.go
  net/node.go
  net/peer.go
  net/server.go
Labels: area/logging

#2740 test: Allow test harness to execute benchmarks
  tests/change_detector/utils.go
  tests/integration/explain.go
  tests/integration/explain_result_asserter.go
  tests/integration/results.go
  tests/integration/state.go
  tests/integration/test_case.go
  tests/integration/utils2.go
Labels: area/testing

#2742 fix: Add version check in basicTxn.Query
  datastore/memory/txn.go
  datastore/memory/txn_test.go
  datastore/txn_test.go
Labels: bug, area/datastore

#2700 refactor: Use events to test network logic
  cli/start.go
  client/db.go
  client/mocks/db.go
  datastore/mocks/utils.go
  event/bus.go
  event/bus_test.go
  event/errors.go
  event/event.go
  events/dag_sync.go
  events/db_update.go
  events/events.go
  events/publisher.go
  events/publisher_test.go
  events/simple.go
  events/simple_test.go
  http/client.go
  http/handler_ccip_test.go
  internal/db/collection.go
  internal/db/collection_delete.go
  internal/db/config.go
  internal/db/config_test.go
  internal/db/db.go
  internal/db/merge.go
  internal/db/merge_test.go
  internal/db/subscriptions.go
  net/client.go
  net/client_test.go
  net/node.go
  net/node_test.go
  net/peer.go
  net/peer_test.go
  net/server.go
  net/sync_dag.go
  tests/clients/cli/wrapper.go
  tests/clients/clients.go
  tests/clients/http/wrapper.go
  tests/integration/db.go
  tests/integration/events/utils.go
  tests/integration/p2p.go
  tests/integration/state.go
  tests/integration/utils2.go
Labels: refactor, area/network

#2743 docs(i): Update contributors
  README.md
Labels: documentation

#2746 fix: Use node representation for Block
  docs/data_format_changes/i2746-use-node-representation.md
  internal/core/block/block.go
  internal/core/block/block_test.go
  internal/db/merge_test.go
  net/sync_dag.go
  tests/integration/events/simple/with_update_test.go
  tests/integration/mutation/create/with_version_test.go
  tests/integration/query/commits/simple_test.go
  tests/integration/query/commits/with_cid_test.go
  tests/integration/query/commits/with_depth_test.go
  tests/integration/query/commits/with_doc_id_cid_test.go
  tests/integration/query/commits/with_doc_id_count_test.go
  tests/integration/query/commits/with_doc_id_field_test.go
  tests/integration/query/commits/with_doc_id_limit_offset_test.go
  tests/integration/query/commits/with_doc_id_limit_test.go
  tests/integration/query/commits/with_doc_id_order_limit_offset_test.go
  tests/integration/query/commits/with_doc_id_order_test.go
  tests/integration/query/commits/with_doc_id_test.go
  tests/integration/query/commits/with_doc_id_typename_test.go
  tests/integration/query/commits/with_field_test.go
  tests/integration/query/commits/with_group_test.go
  tests/integration/query/latest_commits/with_doc_id_field_test.go
  tests/integration/query/latest_commits/with_doc_id_test.go
  tests/integration/query/one_to_many/with_cid_doc_id_test.go
  tests/integration/query/simple/with_cid_doc_id_test.go
  tests/integration/query/simple/with_version_test.go
Labels: bug

#2765 fix: Return slice of correct length from db.AddSchema
  internal/db/collection_define.go
Labels: bug, area/schema

#2772 tools(i): Make one command do all the steps
  Makefile
Labels: code quality

#2773 fix: Change new identity keys to hex format
  acp/identity/generate.go
  cli/identity_new.go
  docs/website/references/cli/defradb_identity_new.md
Labels: refactor

#2776 chore(i): Bump mockery to `v2.43.0` & fix deprecated config
  Makefile
  client/mocks/collection.go
  client/mocks/db.go
  datastore/mocks/dag_store.go
  datastore/mocks/ds_reader_writer.go
  datastore/mocks/results.go
  datastore/mocks/root_store.go
  datastore/mocks/txn.go
  internal/db/fetcher/mocks/encoded_document.go
  internal/db/fetcher/mocks/fetcher.go
  tools/configs/mockery.yaml
Labels: ci/build, dependencies, config-change, deprecate

#2777 fix: Remove shared mutable state between database instances
  internal/request/graphql/schema/collection.go
  internal/request/graphql/schema/descriptions.go
  internal/request/graphql/schema/generate.go
  internal/request/graphql/schema/manager.go
  internal/request/graphql/schema/manager_test.go
  internal/request/graphql/schema/types/base.go
  internal/request/graphql/schema/types/commits.go
  internal/request/graphql/schema/types/scalars.go
  internal/request/graphql/schema/types/scalars_test.go
  internal/request/graphql/schema/types/types.go
  tests/integration/schema/client_test.go
Labels: bug, area/query

#2784 fix: Keyring output
  cli/keyring.go
  cli/keyring_generate.go
  cli/keyring_generate_test.go
  cli/utils.go
  docs/website/references/cli/defradb_keyring.md
  docs/website/references/cli/defradb_keyring_generate.md
Labels: area/cli

#2786 test: Support asserting on doc index in test results
  tests/integration/net/one_to_many/peer/with_create_update_test.go
  tests/integration/utils2.go
Labels: area/testing, code quality

#2787 test: Remove duplicate test
  tests/integration/mutation/update/field_kinds/one_to_many/with_alias_test.go
Labels: area/testing, code quality

#2780 ci(i): Bump all gh-action versions to support node20
  .github/workflows/build-dependencies.yml
  .github/workflows/build-then-deploy-ami.yml
  .github/workflows/check-documentation.yml
  .github/workflows/check-mocks.yml
  .github/workflows/check-tidy.yml
  .github/workflows/check-vulnerabilities.yml
  .github/workflows/combine-bot-prs.yml
  .github/workflows/lint-then-benchmark.yml
  .github/workflows/lint.yml
  .github/workflows/preview-ami-with-terraform-plan.yml
  .github/workflows/release.yml
  .github/workflows/start-binary.yml
  .github/workflows/test-and-upload-coverage.yml
  .github/workflows/validate-containerfile.yml
  .github/workflows/validate-title.yml
Labels: ci/build, deprecate

#2789 ci(i): Make change detector an independent workflow
  .github/workflows/check-data-format-changes.yml
  .github/workflows/test-and-upload-coverage.yml
Labels: ci/build

#2790 ci(i): Remove redundant matrix rule that is repeated
  .github/workflows/test-and-upload-coverage.yml
Labels: ci/build

#2793 docs: Remove reference to client ping from readme
  README.md
Labels: documentation, area/cli

#2788 test: Allow assertion of AddSchema results
  tests/integration/results.go
  tests/integration/schema/simple_test.go
  tests/integration/test_case.go
  tests/integration/utils2.go
Labels: area/schema, area/testing, code quality

#2798 ci(i): Update go releaser
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: ci/build

#2796 fix: Allow primary field declarations on one-many
  internal/request/graphql/schema/collection.go
  tests/integration/results.go
  tests/integration/schema/one_many_test.go
Labels: bug, area/schema

#2799 fix: Support one-many self joins without primary directive
  internal/request/graphql/schema/collection.go
  tests/integration/schema/one_many_test.go
Labels: bug, area/schema

#2791 chore(i): Bump & fix the breaking change of libp2p dep
  go.mod
  go.sum
Labels: dependencies, deprecate, bump
