Repository sourcenetwork/defradb, pull requests merged in 2025-04, with the labels that each got.

#3593 test(i): Wait for database to close before progressing
  cli/test/action/action.go
  cli/test/action/start.go
  cli/test/integration/test.go
  cli/test/state/state.go
Labels: area/testing

#3574 feat: Make replicator retry intervals configurable
  cli/config.go
  cli/errors.go
  cli/start.go
  cli/test/action/action.go
  cli/test/action/start.go
  cli/test/integration/start/replicator_interval_retry/invalid_interval_test.go
  cli/test/integration/start/replicator_interval_retry/negative_interval_test.go
  cli/test/integration/start/replicator_interval_retry/overflow_interval_test.go
  cli/test/integration/start/replicator_interval_retry/simple_test.go
  docs/website/references/cli/defradb_start.md
Labels: feature, area/cli

#3606 fix: PeerInfo sync issue
  net/errors.go
  net/peer.go
Labels: area/p2p

#3617 feat: Configure fallback signer
  cli/config.go
  cli/start.go
  docs/website/references/cli/defradb_start.md
  internal/db/collection.go
  internal/db/collection_delete.go
  internal/db/config.go
  internal/db/db.go
  internal/merkle/clock/clock.go
  internal/merkle/clock/errors.go
  tests/integration/db.go
  tests/integration/signature/commit_test.go
  tests/integration/signature/fallback_signer_test.go
  tests/integration/signature/verify_test.go
  tests/integration/test_case.go
Labels: security

#3629 fix(i): Node identity as default instead of fallback signer
  cli/config.go
  cli/start.go
  docs/website/references/cli/defradb_start.md
  internal/db/collection.go
  internal/db/collection_delete.go
  internal/db/config.go
  internal/db/db.go
  internal/merkle/clock/clock.go
  internal/merkle/clock/errors.go
  tests/integration/db.go
  tests/integration/signature/fallback_signer_test.go
  tests/integration/test_case.go
Labels: bug, area/cli, area/config

#3643 fix: Get indexes for a specific collection
  http/handler_collection.go
  tests/integration/index/create_get_test.go
Labels: bug, area/api

#3653 refactor: Replace schema-only collections with boolean
  client/collection_description.go
  client/definitions.go
  client/schema_description.go
  docs/data_format_changes/i3646-rm-schema-only-cols.md
  docs/website/references/http/openapi.json
  internal/db/definition_validation.go
  internal/planner/mapper/mapper.go
  internal/request/graphql/schema/collection.go
  internal/request/graphql/schema/generate.go
  tests/integration/collection/update/simple/with_filter_test.go
  tests/integration/view/one_to_one/simple_test.go
Labels: area/collections, refactor
