Repository sourcenetwork/defradb, pull requests merged in 2025-01, with the labels that each got.

#3343 chore: Import defradb/errors for Join
  client/definitions.go
  client/document.go
  datastore/prefix_query.go
  http/client_collection.go
  internal/db/description/collection.go
  internal/db/fetcher/indexer_iterators.go
  internal/db/fetcher/multi.go
  internal/db/indexed_docs_test.go
  internal/db/view.go
  internal/request/graphql/schema/manager.go
  node/node.go
Labels: area/errors

#3363 feat: Purge ACP state on DB purge
  acp/acp.go
  acp/acp_local.go
  acp/acp_local_test.go
  acp/acp_source_hub.go
  acp/errors.go
  acp/source_hub_client.go
  node/node.go
Labels: feature, priority/high, area/acp

#3367 fix: Maintain indexes across schema versions
  internal/db/collection_index.go
  internal/db/fetcher/indexer_iterators.go
  internal/db/index.go
  tests/integration/schema/updates/add/field/with_index_test.go
Labels: bug, area/schema, area/collections

#3352 feat: Multiple schema file support in schema add
  cli/errors.go
  cli/schema_add.go
  docs/website/references/cli/defradb_client_schema_add.md
Labels: feature, area/cli

#3390 perf: Remove compound condition from 1-1 validation filter
  internal/db/collection.go
Labels: area/query, perf

#3387 fix: Ensure no ACP doc check when action is node specific
  internal/db/collection_acp.go
  internal/db/p2p_replicator.go
  internal/db/p2p_schema_root.go
Labels: bug, area/acp

#3317 feat: P2P ACP
  acp/identity/identity.go
  http/auth.go
  http/auth_test.go
  internal/db/backup.go
  internal/db/collection.go
  internal/db/collection_define.go
  internal/db/collection_id.go
  internal/db/collection_index.go
  internal/db/db.go
  internal/db/db_test.go
  internal/db/definition_validation.go
  internal/db/index_test.go
  internal/db/lens.go
  internal/db/merge.go
  internal/db/messages.go
  internal/db/p2p_replicator.go
  internal/db/p2p_replicator_test.go
  internal/db/p2p_schema_root.go
  internal/db/permission/check.go
  internal/db/request.go
  internal/db/schema.go
  internal/db/sequence.go
  internal/db/store.go
  internal/db/subscriptions.go
  internal/db/view.go
  net/client.go
  net/dialer_test.go
  net/errors.go
  net/grpc.go
  net/peer.go
  net/peer_test.go
  net/server.go
  net/server_test.go
  net/sync_dag.go
  node/node.go
  tests/integration/acp.go
  tests/integration/acp/p2p/create_test.go
  tests/integration/acp/p2p/subscribe_test.go
  tests/integration/acp/p2p/subscribe_with_doc_actor_relationship_test.go
  tests/integration/encryption/peer_acp_test.go
  tests/integration/events.go
  tests/integration/utils.go
Labels: feature

#3368 feat: Add special encoding of json array elements
  client/json.go
  client/json_test.go
  client/json_traverse_test.go
  client/normal_array.go
  client/normal_new.go
  client/normal_util.go
  client/normal_value.go
  client/normal_value_test.go
  client/normal_void.go
  docs/data_format_changes/i3368-json-array-encoding.md
  internal/connor/none.go
  internal/db/fetcher/indexer_iterators.go
  internal/db/index.go
  internal/db/indexed_docs_test.go
  internal/encoding/errors.go
  internal/encoding/json.go
  internal/encoding/json_test.go
  tests/integration/index/json_array_test.go
  tests/integration/index/json_unique_array_test.go
  tests/integration/query/json/with_none_test.go
Labels: feature, area/query

#3400 fix(i): Fetcher wrapper panic
  internal/db/fetcher/wrapper.go
Labels: bug

#3403 test(i): Handle error in test setup, don't return nil
  tests/integration/db.go
Labels: code quality

#3396 test(i): Test benchmark current local acp operations
  tests/bench/acp/acp_bench_report_20250114.md
  tests/bench/acp/acp_bench_report_20250120.md
  tests/bench/acp/acp_local_test.go
Labels: perf, area/testing
