Repository sourcenetwork/defradb, pull requests merged in 2025-03, with the labels that each got.

#3510 refactor: Changed paths for lens migration in CLI
  cli/cli.go
  cli/lens.go
  cli/lens_down.go
  cli/lens_reload.go
  cli/lens_set.go
  cli/lens_set_registry.go
  cli/lens_up.go
  docs/website/references/cli/defradb_client.md
  docs/website/references/cli/defradb_client_lens.md
  docs/website/references/cli/defradb_client_lens_down.md
  docs/website/references/cli/defradb_client_lens_reload.md
  docs/website/references/cli/defradb_client_lens_set-registry.md
  docs/website/references/cli/defradb_client_lens_set.md
  docs/website/references/cli/defradb_client_lens_up.md
  docs/website/references/cli/defradb_client_schema.md
  tests/clients/cli/wrapper.go
  tests/clients/cli/wrapper_lens.go
Labels: area/cli

#3505 feat: Introduce digital signatures
  cli/config.go
  cli/start.go
  client/request/consts.go
  crypto/errors.go
  crypto/signature.go
  crypto/signature_test.go
  docs/website/references/cli/defradb_start.md
  internal/core/block/block.go
  internal/core/block/block_test.go
  internal/core/block/encryption.go
  internal/core/block/errors.go
  internal/core/block/signature.go
  internal/core/block/signature_test.go
  internal/core/crdt/ipld_union.go
  internal/db/collection.go
  internal/db/config.go
  internal/db/db.go
  internal/db/merge.go
  internal/merkle/clock/clock.go
  internal/merkle/clock/clock_test.go
  internal/merkle/crdt/composite.go
  internal/merkle/crdt/counter.go
  internal/merkle/crdt/lwwreg.go
  internal/planner/commit.go
  internal/planner/mapper/mapper.go
  internal/planner/select.go
  internal/request/graphql/schema/types/commits.go
  internal/request/graphql/schema/types/descriptions.go
  net/peer.go
  net/server.go
  net/sync_dag.go
  tests/integration/db.go
  tests/integration/query/commits/branchables/cid_test.go
  tests/integration/query/commits/branchables/create_test.go
  tests/integration/query/commits/branchables/delete_test.go
  tests/integration/query/commits/branchables/field_id_test.go
  tests/integration/query/commits/branchables/if_test.go
  tests/integration/query/commits/branchables/peer_test.go
  tests/integration/query/commits/branchables/peer_update_test.go
  tests/integration/query/commits/branchables/simple_test.go
  tests/integration/query/commits/branchables/update_test.go
  tests/integration/query/commits/simple_test.go
  tests/integration/query/commits/with_delete_test.go
  tests/integration/results.go
  tests/integration/results_test.go
  tests/integration/signature/branchable_test.go
  tests/integration/signature/commit_test.go
  tests/integration/signature/query_test.go
  tests/integration/signature/utils.go
  tests/integration/state.go
  tests/integration/test_case.go
  tests/integration/utils.go
Labels: feature, security

#3552 fix: Only give badger a path if not in-memory
  node/store_badger.go
Labels: bug, area/db-system

#3550 test: Add example CLI integration tests
  cli/config.go
  cli/start.go
  cli/test/action/action.go
  cli/test/action/collection_describe.go
  cli/test/action/schema_add.go
  cli/test/action/start.go
  cli/test/action/tx_commit.go
  cli/test/action/tx_create.go
  cli/test/action/txn_action.go
  cli/test/integration/schema_add/simple_test.go
  cli/test/integration/start/simple_test.go
  cli/test/integration/test.go
  cli/test/multiplier/multiplier.go
  cli/test/multiplier/txn.go
  cli/test/state/state.go
  docs/website/references/cli/defradb_start.md
  go.mod
  go.sum
Labels: area/testing

#3576 test(i): Add test for same secondary index names
  tests/integration/index/create_test.go
Labels: area/testing
