Repository sourcenetwork/defradb, pull requests merged in 2025-08, with the labels that each got.

#3924 fix(i): Fix acp config flags on start
  cli/start.go
  docs/website/references/cli/defradb_start.md
Labels: area/acp

#3907 refactor: Remove gRPC from net
  go.mod
  go.sum
  net/client.go
  net/client_test.go
  net/codec.go
  net/config/config.go
  net/dialer.go
  net/dialer_test.go
  net/grpc.go
  net/message/errors.go
  net/message/message.go
  net/message/metadata.go
  net/message/metadata_test.go
  net/p2p_replicator.go
  net/peer.go
  net/peer_test.go
  net/protocol/base.go
  net/protocol/identity.go
  net/protocol/replicator.go
  net/server.go
  net/server_test.go
  net/sync_doc.go
Labels: area/p2p, area/network

#3945 chore(i): Lock mockery down to patch version
  Makefile
  client/mocks/collection.go
  client/mocks/txn_store.go
  internal/datastore/mocks/blockstore.go
  internal/db/fetcher/mocks/encoded_document.go
  internal/db/fetcher/mocks/fetcher.go
Labels: ci/build

#3950 refactor: Utilize CGO handles for C bindings
  .github/workflows/test-c-bindings.yml
  .github/workflows/test-coverage.yml
  Makefile
  cbindings/acp.go
  cbindings/block.go
  cbindings/bridge/main.go
  cbindings/bridge/utils.go
  cbindings/collection.go
  cbindings/cutils.go
  cbindings/defra_structs.h
  cbindings/errors.go
  cbindings/identity.go
  cbindings/index.go
  cbindings/lens.go
  cbindings/logic/acp.go
  cbindings/logic/block.go
  cbindings/logic/collection.go
  cbindings/logic/identity.go
  cbindings/logic/lens.go
  cbindings/logic/node.go
  cbindings/logic/p2p.go
  cbindings/logic/schema.go
  cbindings/logic/txn.go
  cbindings/main.go
  cbindings/node.go
  cbindings/p2p.go
  cbindings/query.go
  cbindings/schema.go
  cbindings/test_utils.go
  cbindings/txn.go
  cbindings/utils.go
  cbindings/version.go
  cbindings/view.go
  cbindings/wrapper.go
  cbindings/wrapper_collection.go
  cbindings/wrapper_lens.go
  cbindings/wrapper_tx.go
  tests/clients/c/wrapper.go
  tests/clients/c/wrapper_collection.go
  tests/integration/acp/nac/relation_admin/schema_add_test.go
  tests/integration/acp/nac/schema_add_test.go
  tests/integration/client_setup.go
  tests/integration/client_setup_js.go
  tests/integration/db_setup.go
  tests/integration/db_setup_js.go
  tests/integration/signature/verify_test.go
  tests/integration/utils.go
  tools/scripts/build-c-shared-linux.sh
Labels: area/testing

#3966 feat: Handle invalid CGO handles in C bindings
  cbindings/acp.go
  cbindings/block.go
  cbindings/collection.go
  cbindings/cutils.go
  cbindings/errors.go
  cbindings/identity.go
  cbindings/index.go
  cbindings/lens.go
  cbindings/node.go
  cbindings/p2p.go
  cbindings/query.go
  cbindings/schema.go
  cbindings/view.go
Labels: code quality
