Repository sourcenetwork/defradb, pull requests merged in 2025-02, with the labels that each got.

#3431 feat(i): Add telemetry release config
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: release

#3444 chore: Bump to GoLang v1.23
  go.mod
  tools/cloud/aws/packer/build_aws_ami.pkr.hcl
  tools/configs/golangci.yaml
  tools/defradb.containerfile
Labels: bump

#3466 fix: Make --no-encryption flag work without keyring
  cli/start.go
Labels: bug

#3464 feat: Add cosine similarity query
  client/request/consts.go
  client/request/similarity.go
  internal/planner/errors.go
  internal/planner/mapper/mapper.go
  internal/planner/mapper/similarity.go
  internal/planner/operations.go
  internal/planner/planner.go
  internal/planner/scan.go
  internal/planner/select.go
  internal/planner/similarity.go
  internal/request/graphql/parser/query.go
  internal/request/graphql/parser/request.go
  internal/request/graphql/schema/generate.go
  internal/request/graphql/schema/types/types.go
  tests/integration/explain/execute/with_similarity_test.go
  tests/integration/query/simple/with_similarity_test.go
  tests/integration/schema/default_fields.go
  tests/integration/schema/similarity_test.go
Labels: area/query, area/parser, area/mapper, area/planner

#3463 tools(i): Simplify releases
  .goreleaser.yaml
  tools/defradb.containerfile
Labels: release

#3473 test(i): Fix debug explain test-framework with similarity
  internal/planner/explain.go
  tests/integration/explain.go
  tests/integration/explain/debug/with_similarity_test.go
Labels: bug, area/testing

#3474 fix: Updating of document via cli
  cli/collection_update.go
  cli/errors.go
  docs/website/references/cli/defradb_client_collection_update.md
  internal/db/collection_update.go
  tests/clients/cli/wrapper_collection.go
  tests/integration/collection/update/simple/utils.go
  tests/integration/collection/update/simple/with_filter_test.go
Labels: bug

#3446 chore(i): Bump golangci-lint to v1.64
  .github/workflows/lint.yml
  Makefile
  tests/integration/results.go
  tools/configs/golangci.yaml
Labels: code quality, bump

#3477 fix: Consistent version query semantics
  docs/data_format_changes/i3477-version-query-consistency.md
  internal/planner/commit.go
  internal/planner/errors.go
  internal/planner/select.go
  tests/integration/query/commits/branchables/cid_doc_id_test.go
  tests/integration/query/commits/with_cid_test.go
  tests/integration/query/commits/with_doc_id_cid_test.go
  tests/integration/query/simple/with_cid_doc_id_test.go
Labels: bug, area/query

#3479 fix(i): Release cache path
  .github/workflows/release.yml
Labels: ci/build

#3489 test: Incorporate gomega matchers
  go.mod
  tests/integration/encryption/peer_test.go
  tests/integration/mutation/create/embeddings/embedding_test.go
  tests/integration/mutation/update/embeddings/embedding_test.go
  tests/integration/net/simple/peer/with_update_test.go
  tests/integration/results.go
  tests/integration/test_case.go
  tests/integration/utils.go
Labels: area/testing
